---
sidebar: sidebar 
permalink: cli-upgrade-esxi.html 
keywords: administer, administering, cli, esxi, upgrade, esxi 7.0 
summary: VMware ESXi에서 ONTAP Select 실행 중인 경우, ESXi 소프트웨어를 이전 지원 버전에서 ESXi 7.0 이상으로 업그레이드할 수 있습니다. 업그레이드하기 전에 프로세스를 이해하고 적절한 업그레이드 절차를 선택해야 합니다. 
---
= ONTAP Select 위해 VMware ESXi 7.0 이상으로 업그레이드하세요.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMware ESXi에서 ONTAP Select 실행 중인 경우, ESXi 소프트웨어를 이전 지원 버전에서 ESXi 7.0 이상으로 업그레이드할 수 있습니다. 업그레이드하기 전에 프로세스를 이해하고 적절한 업그레이드 절차를 선택해야 합니다.



== VMware ESXi 업그레이드 준비

ONTAP Select 클러스터를 호스팅하는 하이퍼바이저에서 ESXi 소프트웨어를 업그레이드하기 전에 사용자 환경에 적합한 업그레이드 절차를 준비하고 선택하세요.

.단계
. *VMware ESXi 업그레이드 방법을 알아보세요*
+
ESXi 소프트웨어 업그레이드는 VMware에서 설명하고 지원하는 프로세스입니다. 하이퍼바이저 업그레이드 프로세스는 ONTAP Select 사용할 때 더 큰 업그레이드 절차의 일부입니다. 자세한 내용은 VMware 설명서를 참조하십시오.

. *업그레이드 절차를 선택하세요*
+
여러 가지 업그레이드 절차가 있습니다. 다음 기준에 따라 적합한 절차를 선택해야 합니다.

+
** ONTAP Select 단일 노드 클러스터와 다중 노드 클러스터가 모두 지원됩니다.
** ONTAP Select Deploy 사용
+
Deploy 유틸리티를 사용하거나 사용하지 않고도 업그레이드가 가능합니다.

+

TIP: Deploy 관리 유틸리티를 사용하는 업그레이드 절차를 선택해야 합니다.

+
Deploy 관리 유틸리티를 사용하여 ESXi 업그레이드를 수행하는 것이 더 일반적이고 복원력이 뛰어난 옵션입니다. 하지만 Deploy를 사용할 수 없거나 사용할 수 없는 경우가 있을 수 있습니다. 예를 들어, 이전 버전의 ONTAP Select 및 Deploy 관리 유틸리티에서는 ESXi 7.0으로의 업그레이드가 지원되지 않습니다.

+
이전 버전을 사용 중이고 업그레이드를 시도하면 ONTAP Select 가상 머신이 부팅되지 않는 상태로 남을 수 있습니다. 이 경우, Deploy를 사용하지 않는 업그레이드 절차를 선택해야 합니다. 참조하다link:https://mysupport.netapp.com/site/bugs-online/product/ONTAPSELECT/BURT/1172198["1172198"^] 자세한 내용은.



. *Deploy 관리 유틸리티 업그레이드*
+
Deploy 유틸리티를 사용하여 업그레이드 절차를 수행하기 전에 Deploy 인스턴스를 업그레이드해야 할 수도 있습니다. 일반적으로 최신 버전의 Deploy로 업그레이드해야 합니다. Deploy 유틸리티는 사용 중인 ONTAP Select 버전을 지원해야 합니다. 를 참조하세요link:reference_release_notes.html["ONTAP Select 릴리스 노트"] 자세한 내용은.

. *업데이트 절차가 완료된 후*
+
Deploy 유틸리티를 사용하는 업그레이드 절차를 선택하는 경우, 모든 노드가 업그레이드된 후 Deploy 유틸리티를 사용하여 클러스터 새로 고침 작업을 수행해야 합니다. 자세한 내용은 Deploy 클러스터 구성 새로 고침을 참조하십시오.





== Deploy를 사용하여 단일 노드 클러스터 업그레이드

ONTAP Select 단일 노드 클러스터를 호스팅하는 VMware ESXi 하이퍼바이저를 업그레이드하는 절차의 일부로 Deploy 관리 유틸리티를 사용할 수 있습니다.

.단계
. 관리자 계정으로 SSH를 사용하여 Deploy 유틸리티 CLI에 Sign in .
. 노드를 오프라인 상태로 이동합니다.
+
[source, cli]
----
node stop --cluster-name <cluster_name> --node-name <node_name>
----
. VMware에서 제공하는 절차를 사용하여 ONTAP Select 실행되는 하이퍼바이저 호스트를 ESXi 7.0 이상으로 업그레이드합니다.
. 노드를 온라인 상태로 이동합니다.
+
[source, cli]
----
node start --cluster-name <cluster_name> --node-name <node_name>
----
. 노드가 활성화되면 클러스터가 정상인지 확인하세요.
+
예:

+
....
ESX-1N::> cluster show
Node           Health  Eligibility
-------------- ------- ------------
sdot-d200-011d true    true
....


.당신이 완료한 후
Deploy 관리 유틸리티를 사용하여 클러스터 새로 고침 작업을 수행해야 합니다.



== Deploy를 사용하여 다중 노드 클러스터 업그레이드

ONTAP Select 다중 노드 클러스터를 호스팅하는 VMware ESXi 하이퍼바이저를 업그레이드하는 절차의 일부로 Deploy 관리 유틸리티를 사용할 수 있습니다.

.이 작업에 관하여
클러스터의 각 노드에 대해 한 번에 한 노드씩 이 업그레이드 절차를 수행해야 합니다. 클러스터에 네 개 이상의 노드가 있는 경우, 다음 HA 쌍으로 진행하기 전에 각 HA 쌍의 노드를 순차적으로 업그레이드해야 합니다.

.단계
. 관리자 계정으로 SSH를 사용하여 Deploy 유틸리티 CLI에 Sign in .
. 노드를 오프라인 상태로 이동합니다.
+
[source, cli]
----
node stop --cluster-name <cluster_name> --node-name <node_name>
----
. VMware에서 제공하는 절차를 사용하여 ONTAP Select 실행되는 하이퍼바이저 호스트를 ESXi 7.0 이상으로 업그레이드합니다.
+
자세한 내용은 VMware ESXi 업그레이드 준비를 참조하세요.

. 노드를 온라인 상태로 이동합니다.
+
[source, cli]
----
node start --cluster-name <cluster_name> --node-name <node_name>
----
. 노드가 작동한 후 스토리지 장애 조치가 활성화되었고 클러스터가 정상인지 확인하세요.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
ESX-2N_I2_N11N12::> storage failover show
Takeover
Node Partner Possible State Description
-------------- -------------- -------- ---------------------------
sdot-d200-011d sdot-d200-012d true Connected to sdot-d200-012d
sdot-d200-012d sdot-d200-011d true Connected to sdot-d200-011d
2 entries were displayed.
ESX-2N_I2_N11N12::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
sdot-d200-012d true true
2 entries were displayed.
----
====


.당신이 완료한 후
ONTAP Select 클러스터에 사용된 각 호스트에 대해 업그레이드 절차를 수행해야 합니다. 모든 ESXi 호스트가 업그레이드된 후에는 Deploy 관리 유틸리티를 사용하여 클러스터 새로 고침 작업을 수행해야 합니다.



== 배포 없이 단일 노드 클러스터 업그레이드

Deploy 관리 유틸리티를 사용하지 않고도 ONTAP Select 단일 노드 클러스터를 호스팅하는 VMware ESXi 하이퍼바이저를 업그레이드할 수 있습니다.

.단계
. ONTAP 명령줄 인터페이스에 Sign in 노드를 중지합니다.
. VMware vSphere를 사용하여 ONTAP Select 가상 머신의 전원이 꺼져 있는지 확인합니다.
. VMware에서 제공하는 절차를 사용하여 ONTAP Select 실행되는 하이퍼바이저 호스트를 ESXi 7.0 이상으로 업그레이드합니다.
+
자세한 내용은 VMware ESXi 업그레이드 준비를 참조하세요.

. VMware vSphere를 사용하여 vCenter에 액세스하고 다음을 수행합니다.
+
.. ONTAP Select 가상 머신에 플로피 드라이브를 추가합니다.
.. ONTAP Select 가상 머신의 전원을 켭니다.
.. 관리자 계정으로 SSH를 사용하여 ONTAP CLI에 Sign in .


. 노드가 활성화되면 클러스터가 정상인지 확인하세요.
+
예:

+
....
ESX-1N::> cluster show
Node           Health  Eligibility
-------------- ------- ------------
sdot-d200-011d true    true
....


.당신이 완료한 후
Deploy 관리 유틸리티를 사용하여 클러스터 새로 고침 작업을 수행해야 합니다.



== 배포 없이 다중 노드 클러스터 업그레이드

Deploy 관리 유틸리티를 사용하지 않고도 ONTAP Select 다중 노드 클러스터를 호스팅하는 VMware ESXi 하이퍼바이저를 업그레이드할 수 있습니다.

.이 작업에 관하여
클러스터의 각 노드에 대해 한 번에 한 노드씩 이 업그레이드 절차를 수행해야 합니다. 클러스터에 네 개 이상의 노드가 있는 경우, 다음 HA 쌍으로 진행하기 전에 각 HA 쌍의 노드를 순차적으로 업그레이드해야 합니다.

.단계
. ONTAP 명령줄 인터페이스에 Sign in 노드를 중지합니다.
. VMware vSphere를 사용하여 ONTAP Select 가상 머신의 전원이 꺼져 있는지 확인합니다.
. VMware에서 제공하는 절차를 사용하여 ONTAP Select 실행되는 하이퍼바이저 호스트를 ESXi 7.0 이상으로 업그레이드합니다.
. VMware vSphere를 사용하여 vCenter에 액세스하고 다음을 수행합니다.
+
.. ONTAP Select 가상 머신에 플로피 드라이브를 추가합니다.
.. ONTAP Select 가상 머신의 전원을 켭니다.
.. 관리자 계정으로 SSH를 사용하여 ONTAP CLI에 Sign in .


. 노드가 작동한 후 스토리지 장애 조치가 활성화되었고 클러스터가 정상인지 확인하세요.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
ESX-2N_I2_N11N12::> storage failover show
Takeover
Node Partner Possible State Description
-------------- -------------- -------- ---------------------------
sdot-d200-011d sdot-d200-012d true Connected to sdot-d200-012d
sdot-d200-012d sdot-d200-011d true Connected to sdot-d200-011d
2 entries were displayed.
ESX-2N_I2_N11N12::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
sdot-d200-012d true true
2 entries were displayed.
----
====


.당신이 완료한 후
ONTAP Select 클러스터에 사용된 각 호스트에 대해 업그레이드 절차를 수행해야 합니다.
