---
sidebar: sidebar 
permalink: concept_usecase_overview.html 
keywords: ontap select, business use case overview, deployment, storage, development and testing 
summary: ONTAP Select 하이퍼바이저 가상화를 통해 제공되는 고유한 유연성을 기반으로 여러 유형의 애플리케이션에 적합합니다. 
---
= ONTAP Select 비즈니스 요구 사항 및 사용 시나리오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 하이퍼바이저 가상화를 통해 제공되는 고유한 유연성을 기반으로 여러 유형의 애플리케이션에 적합합니다.



== 전개

높은 수준에서 하이퍼바이저 호스트 서버의 작업 부하와 관련하여 ONTAP Select 두 가지 다른 방법으로 배포할 수 있습니다.



=== 전담 배치

전용 배포 모델을 사용하면 ONTAP Select 의 단일 인스턴스가 호스트 서버에서 실행됩니다. 다른 중요한 처리 작업은 동일한 하이퍼바이저 호스트에서 실행되지 않습니다.



=== 공동 배치

공동 배치 배포 모델에서 ONTAP Select 다른 워크로드와 호스트를 공유합니다. 구체적으로, 일반적으로 컴퓨팅 애플리케이션을 실행하는 추가 가상 머신이 있습니다. 이러한 컴퓨팅 워크로드는 ONTAP Select 클러스터에 로컬로 존재합니다. 이 모델은 특수 애플리케이션 및 배포 요구 사항을 지원합니다. 전용 배포 모델과 마찬가지로, 각 ONTAP Select 가상 머신은 별도의 전용 하이퍼바이저 호스트에서 실행되어야 합니다.



== 스토리지

ONTAP Select 비즈니스 요구 사항에 따라 기본 또는 보조 스토리지로 사용할 수 있습니다.



=== 1차 저장소

경우에 따라 ONTAP Select 기본 스토리지 플랫폼으로 구축할 수 있습니다. 이러한 구현 유형은 애플리케이션의 워크로드 특성과 비즈니스 목표에 따라 달라집니다.



=== 재해 복구 및 보조 저장소

ONTAP Select 사용하면 기본 스토리지 용량을 확장하는 추가 스토리지를 구축할 수 있습니다. 추가 스토리지는 조직의 재해 복구 작업 및 데이터 백업 계획을 지원하는 데 사용할 수 있습니다.



== 개발 및 테스트

조직 내에서 다양한 애플리케이션을 배포할 때 ONTAP Select 전체 애플리케이션 개발 및 테스트 프로세스의 필수적인 부분으로 활용할 수 있습니다. 예를 들어, 테스트 입력 또는 출력 데이터를 보관할 임시 스토리지가 필요할 수 있습니다. 이러한 유형의 배포 기간은 애플리케이션 특성 및 요구 사항에 따라 달라질 수 있습니다.
