---
sidebar: sidebar 
permalink: concept_ots_deploy.html 
keywords: ontap select deploy, deploy administration utility, deploy utility, functionality, accessing 
summary: ONTAP Select Deploy는 ONTAP Select 클러스터를 배포하고 관리하는 데 사용되는 관리 유틸리티입니다. 
---
= ONTAP Select 배포
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deploy는 ONTAP Select 클러스터를 배포하고 관리하는 데 사용되는 관리 유틸리티입니다. Deploy는 Linux 가상 머신으로 패키징되어 있으며, ONTAP Select 클러스터를 생성하기 전에 설치해야 합니다.



== 핵심 기능

Deploy 관리 유틸리티는 다음과 같은 핵심 기능을 수행합니다.

* ONTAP Select 배포된 각 하이퍼바이저 호스트의 세부 정보를 기록합니다.
* 호스트를 구성하고 필요한 라이센스를 설치합니다.
* ONTAP Select 클러스터 배포 및 관리
* ONTAP Select 클러스터 및 호스트 인벤토리 유지
* AutoSupport 데이터를 수집하여 NetApp 으로 전송
* ONTAP Select 노드 이미지의 내부 세트를 유지합니다.
* 하이퍼바이저별 명령 형식 및 프로토콜 지원




== Deploy 유틸리티에 액세스할 수 있는 방법

Deploy 관리 유틸리티에 액세스할 때 여러 옵션을 사용할 수 있습니다. 모든 외부 인터페이스는 기능적으로 동일합니다. 특정 배포 목표 및 요구 사항에 가장 적합한 액세스 옵션을 선택해야 합니다. 어떤 경우든 유효한 비밀번호를 사용하여 관리자 계정으로 로그인해야 합니다.



=== 웹 그래픽 사용자 인터페이스

최신 웹 브라우저를 통해 Deploy 유틸리티에 접속할 수 있습니다. 웹 UI는 직관적이고 사용하기 쉬운 인터페이스를 제공하며, 대부분의 경우 유틸리티 사용 시 기본 인터페이스로 사용됩니다.



=== 명령줄 인터페이스

관리 셸을 통해 텍스트 기반 명령줄 인터페이스를 사용할 수 있습니다. CLI 관리 셸에 접근하는 방법은 다음과 같습니다.

* 보안 셸(SSH)
* 가상 머신 콘솔


일반적으로 가상 머신 콘솔은 설치 및 초기 구성 과정의 일부로 사용됩니다. 하지만 대부분의 경우 SSH는 더 유연하고 편리한 옵션을 제공합니다.



=== REST 웹 서비스 API

외부 클라이언트에 노출된 REST 웹 서비스 API는 Deploy 유틸리티에 연결할 때 또 다른 옵션을 제공합니다. REST 웹 서비스를 지원하는 모든 주요 프로그래밍 언어나 도구를 사용하여 API에 액세스할 수 있습니다. 자주 사용되는 옵션은 다음과 같습니다.

* 파이썬
* 자바
* 컬


프로그래밍이나 스크립팅 언어를 사용하면 ONTAP Select 클러스터의 배포 및 관리를 자동화할 수 있습니다.



=== ONTAP Select 온라인 문서 웹 페이지

Deploy 유틸리티에서 온라인 문서 웹 페이지를 표시하는 것은 REST 웹 서비스 API에 액세스하는 또 다른 방법입니다. 하지만 프로그래밍 언어를 사용하는 대신 브라우저를 사용하여 해당 페이지를 통해 관리 API에 액세스합니다. 다음과 같은 기능이 제공됩니다.

* REST 웹 서비스 API의 모든 호출에 대한 자세한 설명
* 모든 API 호출을 수동으로 발행하는 기능


Deploy 가상 머신의 IP 또는 도메인 이름을 사용하여 온라인 설명서 페이지에 액세스할 수 있습니다. 페이지를 표시하려면 브라우저에 다음 형식의 URL을 입력하세요(Deploy VM 인스턴스에 적합한 IP 주소 또는 도메인 이름으로 대체). `\http://<ip_address>/api/ui`
