---
sidebar: sidebar 
permalink: concept_stor_eff_support.html 
keywords: ontap select, storage efficiency support 
summary: ONTAP Select FAS 및 AFF 어레이에 있는 스토리지 효율성 옵션과 유사한 스토리지 효율성 옵션을 제공합니다. 
---
= ONTAP Select 스토리지 효율성 지원
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select FAS 및 AFF 어레이에 있는 스토리지 효율성 옵션과 유사한 스토리지 효율성 옵션을 제공합니다.

올플래시 VSAN 또는 일반 플래시 어레이를 사용하는 ONTAP Select 가상 NAS(vNAS) 배포는 SSD가 아닌 직접 연결 스토리지(DAS)를 사용하는 ONTAP Select 의 모범 사례를 따라야 합니다.

DAS 스토리지에 SSD 드라이브와 프리미엄 라이선스가 있는 경우, 새로운 설치 시 AFF 와 유사한 특성이 자동으로 활성화됩니다.

AFF 와 유사한 성격을 지닌 다음 인라인 SE 기능은 설치 중에 자동으로 활성화됩니다.

* 인라인 제로 패턴 감지
* 볼륨 인라인 중복 제거
* 볼륨 백그라운드 중복 제거
* 적응형 인라인 압축
* 인라인 데이터 압축
* 집계 인라인 중복 제거
* 집계 백그라운드 중복 제거


ONTAP Select 모든 기본 스토리지 효율성 정책을 활성화했는지 확인하려면 새로 만든 볼륨에서 다음 명령을 실행합니다.

[listing]
----
<system name>::> set diag
Warning: These diagnostic commands are for use by NetApp personnel only.
Do you want to continue? {y|n}: y
twonode95IP15::*> sis config
Vserver:                                SVM1
Volume:                                 _export1_NFS_volume
Schedule                                -
Policy:                                 auto
Compression:                            true
Inline Compression:                     true
Compression Type:                       adaptive
Application IO Si                       8K
Compression Algorithm:                  lzopro
Inline Dedupe:                          true
Data Compaction:                        true
Cross Volume Inline Deduplication:      true
Cross Volume Background Deduplication:  true
----

NOTE: 9.6 이상에서 ONTAP Select 업그레이드하려면 프리미엄 라이선스를 사용하여 DAS SSD 스토리지에 ONTAP Select 설치해야 합니다. 또한 ONTAP Deploy를 사용하여 초기 클러스터를 설치하는 동안 *스토리지 효율성 사용* 확인란을 선택해야 합니다. 이전 조건이 충족되지 않은 경우 ONTAP 업그레이드 후 AFF 와 유사한 특성을 사용하려면 부팅 인수를 수동으로 생성하고 노드를 재부팅해야 합니다. 자세한 내용은 기술 지원팀에 문의하십시오.

.ONTAP Select 스토리지 효율성 구성
다음 표는 미디어 유형과 소프트웨어 라이선스에 따라 기본적으로 활성화되어 있거나 기본적으로 활성화되어 있지 않지만 권장되는 다양한 저장 효율성 옵션을 요약한 것입니다.

[cols="4"]
|===
| ONTAP Select 기능 | DAS SSD(프리미엄 또는 프리미엄 XL^1^) | DAS HDD(모든 라이선스) | vNAS(모든 라이선스) 


| 인라인 제로 감지 | 예(기본값) | 예 사용자가 볼륨별로 활성화함 | 예 사용자가 볼륨별로 활성화함 


| 볼륨 인라인 중복 제거 | 예(기본값) | 사용할 수 없음 | 지원되지 않음 


| 32K 인라인 압축(2차 압축) | 예, 사용자가 볼륨별로 활성화합니다. | 예 사용자가 볼륨별로 활성화함 | 지원되지 않음 


| 8K 인라인 압축(적응형 압축) | 예(기본값) | 예 사용자가 볼륨별로 활성화함 | 지원되지 않음 


| 배경 압축 | 지원되지 않음 | 예 사용자가 볼륨별로 활성화함 | 예 사용자가 볼륨별로 활성화함 


| 압축 스캐너 | 예 | 예 | 예 사용자가 볼륨별로 활성화함 


| 인라인 데이터 압축 | 예(기본값) | 예 사용자가 볼륨별로 활성화함 | 지원되지 않음 


| 압축 스캐너 | 예 | 예 | 지원되지 않음 


| 집계 인라인 중복 제거 | 예(기본값) | 해당 없음 | 지원되지 않음 


| 볼륨 백그라운드 중복 제거 | 예(기본값) | 예 사용자가 볼륨별로 활성화함 | 예 사용자가 볼륨별로 활성화함 


| 집계 백그라운드 중복 제거 | 예(기본값) | 해당 없음 | 지원되지 않음 
|===
[small]#^1^ ONTAP Select 9.6은 새로운 라이선스(프리미엄 XL)와 새로운 VM 크기(대형)를 지원합니다. 하지만 대형 VM은 소프트웨어 RAID를 사용하는 DAS 구성에서만 지원됩니다. 하드웨어 RAID 및 vNAS 구성은 9.6 릴리스의 대형 ONTAP Select VM에서 지원되지 않습니다.#

.DAS SSD 구성에 대한 업그레이드 동작에 대한 참고 사항
ONTAP Select 9.6 이상으로 업그레이드한 후 다음을 기다리십시오. `system node upgrade-revert show` 기존 볼륨의 저장 효율성 값을 검증하기 전에 업그레이드가 완료되었음을 나타내는 명령입니다.

ONTAP Select 9.6 이상으로 업그레이드된 시스템에서는 기존 집계에 생성된 새 볼륨이나 새로 생성된 집계가 새로 배포된 볼륨과 동일한 동작을 합니다. ONTAP Select 코드 업그레이드를 거치는 기존 볼륨은 새로 생성된 볼륨과 거의 동일한 스토리지 효율성 정책을 가지지만, 다음과 같은 몇 가지 차이점이 있습니다.

시나리오 1:: 업그레이드 전에 볼륨에 스토리지 효율성 정책이 활성화되지 않은 경우:
+
--
* 볼륨이 있는 `space guarantee = volume` 인라인 데이터 압축, 집계 인라인 중복 제거, 집계 백그라운드 중복 제거가 활성화되어 있지 않습니다. 이러한 옵션은 업그레이드 후에 활성화할 수 있습니다.
* 볼륨이 있는 `space guarantee = none` 백그라운드 압축이 활성화되어 있지 않습니다. 이 옵션은 업그레이드 후에 활성화할 수 있습니다.
* 업그레이드 후 기존 볼륨의 스토리지 효율성 정책이 자동으로 설정됩니다.


--
시나리오 2:: 업그레이드 전에 볼륨에서 일부 스토리지 효율성이 이미 활성화된 경우:
+
--
* 볼륨이 있는 `space guarantee = volume` 업그레이드 후 아무런 차이도 보이지 않습니다.
* 볼륨이 있는 `space guarantee = none` 집계 백그라운드 중복 제거를 켜 두세요.
* 볼륨이 있는 `storage policy inline-only` 정책을 자동으로 설정해 놓았습니다.
* 사용자 정의 스토리지 효율성 정책이 있는 볼륨은 정책이 변경되지 않습니다. 단, 다음 볼륨은 예외입니다. `space guarantee = none` . 이러한 볼륨에는 집계 백그라운드 중복 제거가 활성화되어 있습니다.


--

