---
sidebar: sidebar 
permalink: concept_api_async_proc.html 
keywords: rest api, deploy rest api, rest, asynchronous processing, job object 
summary: 일부 Deploy API 호출, 특히 리소스를 생성하거나 수정하는 호출은 다른 호출보다 완료하는 데 시간이 더 오래 걸릴 수 있습니다. ONTAP Select Deploy는 이러한 장기 실행 요청을 비동기적으로 처리합니다. 
---
= ONTAP Select 위한 Job 객체를 사용한 비동기 처리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
일부 Deploy API 호출, 특히 리소스를 생성하거나 수정하는 호출은 다른 호출보다 완료하는 데 시간이 더 오래 걸릴 수 있습니다. ONTAP Select Deploy는 이러한 장기 실행 요청을 비동기적으로 처리합니다.



== Job 객체를 사용하여 설명된 비동기 요청

비동기적으로 실행되는 API 호출 후 HTTP 응답 코드 202는 요청이 성공적으로 검증되고 수락되었지만 아직 완료되지 않았음을 나타냅니다. 요청은 클라이언트에 대한 초기 HTTP 응답 이후에도 계속 실행되는 백그라운드 작업으로 처리됩니다. 응답에는 요청을 앵커링하는 Job 객체와 고유 식별자가 포함됩니다.


NOTE: 어떤 API 호출이 비동기적으로 작동하는지 확인하려면 ONTAP Select Deploy 온라인 설명서 페이지를 참조하세요.



== API 요청과 연관된 Job 객체를 쿼리합니다.

HTTP 응답으로 반환되는 Job 객체에는 여러 속성이 포함되어 있습니다. state 속성을 쿼리하여 요청이 성공적으로 완료되었는지 확인할 수 있습니다. Job 객체는 다음 상태 중 하나일 수 있습니다.

* 대기 중
* 달리기
* 성공
* 실패


작업의 최종 상태(성공 또는 실패)를 감지하기 위해 Job 객체를 폴링할 때 사용할 수 있는 두 가지 기술이 있습니다.

* 표준 폴링 요청 현재 작업 상태가 즉시 반환됩니다.
* 롱 폴링 요청 작업 상태는 다음 중 하나가 발생할 때만 반환됩니다.
+
** 여론조사 요청에 제공된 날짜-시간 값보다 최근에 상태가 변경되었습니다.
** 시간 초과 값이 만료되었습니다(1~120초)




표준 폴링과 롱 폴링은 동일한 API 호출을 사용하여 Job 객체를 쿼리합니다. 그러나 긴 폴링 요청에는 두 개의 쿼리 매개변수가 포함됩니다. `poll_timeout` 그리고 `last_modified` .


TIP: 배포 가상 머신의 작업 부하를 줄이려면 항상 롱 폴링을 사용해야 합니다.



== 비동기 요청을 발행하기 위한 일반 절차

다음의 고급 절차를 사용하여 비동기 API 호출을 완료할 수 있습니다.

. 비동기 API 호출을 실행합니다.
. 요청이 성공적으로 수락되었음을 나타내는 HTTP 응답 202를 받습니다.
. 응답 본문에서 Job 객체의 식별자를 추출합니다.
. 루프 내에서 각 사이클마다 다음을 수행합니다.
+
.. 롱폴 요청으로 Job의 현재 상태를 가져옵니다.
.. 작업이 종료 상태가 아닌 상태(대기 중, 실행 중)인 경우 루프를 다시 수행합니다.


. 작업이 최종 상태(성공, 실패)에 도달하면 중지됩니다.

