---
sidebar: sidebar 
permalink: concept_nw_internal_external.html 
keywords: ontap select, internal network, external network 
summary: 내부 및 외부 ONTAP Select 네트워크의 특성. 
---
= ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select .



== ONTAP Select

제품의 다중 노드 버전에만 존재하는 내부 ONTAP Select 네트워크는 ONTAP Select 클러스터에 클러스터 통신, HA 상호 연결 및 동기 복제 서비스를 제공합니다. 이 네트워크에는 다음과 같은 포트와 인터페이스가 포함됩니다.

* *e0c, e0d.* 클러스터 네트워크 LIF 호스팅
* *이게 뭐야.* RSM LIF 호스팅
* *e0f.* HA 상호 연결 LIF 호스팅


이 네트워크의 처리량과 지연 시간은 ONTAP Select 클러스터의 성능과 복원력을 결정하는 데 매우 중요합니다. 클러스터 보안을 유지하고 시스템 인터페이스를 다른 네트워크 트래픽과 분리하기 위해서는 네트워크 격리가 필수적입니다. 따라서 이 네트워크는 ONTAP Select 클러스터에서만 사용해야 합니다.


NOTE: Select 클러스터 트래픽 이외의 트래픽(예: 애플리케이션 또는 관리 트래픽)에 Select 내부 네트워크를 사용하는 것은 지원되지 않습니다. ONTAP 내부 VLAN에는 다른 VM이나 호스트가 있을 수 없습니다.

내부 네트워크를 통과하는 네트워크 패킷은 전용 VLAN 태그가 지정된 레이어 2 네트워크에 있어야 합니다. 이는 다음 작업 중 하나를 완료하여 달성할 수 있습니다.

* 내부 가상 NIC(e0c~e0f)에 VLAN 태그가 지정된 포트 그룹 할당(VST 모드)
* 네이티브 VLAN이 다른 트래픽에 사용되지 않는 업스트림 스위치에서 제공하는 네이티브 VLAN을 사용합니다(VLAN ID가 없는 포트 그룹 할당, 즉 EST 모드).


모든 경우에 내부 네트워크 트래픽에 대한 VLAN 태그 지정은 ONTAP Select VM 외부에서 수행됩니다.


NOTE: ESX 표준 및 분산형 vSwitch만 지원됩니다. 다른 가상 스위치 또는 ESX 호스트 간의 직접 연결은 지원되지 않습니다. 내부 네트워크는 완전히 개방되어야 하며, NAT 또는 방화벽은 지원되지 않습니다.

ONTAP Select 클러스터 내에서 내부 트래픽과 외부 트래픽은 포트 그룹이라는 가상 레이어 2 네트워크 객체를 사용하여 분리됩니다. 이러한 포트 그룹의 적절한 vSwitch 할당은 특히 클러스터, HA 상호 연결 및 미러 복제 서비스를 제공하는 내부 네트워크의 경우 매우 중요합니다. 이러한 네트워크 포트에 대한 네트워크 대역폭이 부족하면 성능이 저하되고 클러스터 노드의 안정성에 영향을 미칠 수 있습니다. 따라서 4노드, 6노드 및 8노드 클러스터는 내부 ONTAP Select 네트워크에서 10Gb 연결을 사용해야 하며, 1Gb NIC는 지원되지 않습니다. 그러나 ONTAP Select 클러스터로 들어오는 데이터 흐름을 제한하더라도 안정적인 작동에는 영향을 미치지 않으므로 외부 네트워크의 장단점을 고려할 수 있습니다.

2노드 클러스터는 내부 트래픽에 1Gb 포트 4개를 사용하거나, 4노드 클러스터에 필요한 10Gb 포트 2개 대신 10Gb 포트 1개를 사용할 수 있습니다. 서버에 10Gb NIC 카드 4개를 장착할 수 없는 환경에서는 내부 네트워크에 10Gb NIC 카드 2개를, 외부 ONTAP 네트워크에 1Gb NIC 카드 2개를 사용할 수 있습니다.



=== 내부 네트워크 검증 및 문제 해결

다중 노드 클러스터의 내부 네트워크는 네트워크 연결 검사기 기능을 사용하여 검증할 수 있습니다. 이 기능은 Deploy CLI를 실행하여 호출할 수 있습니다. `network connectivity-check start` 명령.

테스트 출력을 보려면 다음 명령을 실행하세요.

[listing]
----
network connectivity-check show --run-id X (X is a number)
----
이 도구는 다중 노드 Select 클러스터의 내부 네트워크 문제 해결에만 유용합니다. 단일 노드 클러스터(vNAS 구성 포함), ONTAP Deploy to ONTAP Select 연결 또는 클라이언트 측 연결 문제를 해결하는 데는 이 도구를 사용해서는 안 됩니다.

클러스터 생성 마법사( ONTAP Deploy UI의 일부)에는 다중 노드 클러스터 생성 중 사용 가능한 선택적 단계인 내부 네트워크 검사기가 포함되어 있습니다. 다중 노드 클러스터 에서 내부 네트워크가 중요한 역할을 한다는 점을 고려할 때, 이 단계를 클러스터 생성 워크플로에 포함시키면 클러스터 생성 작업의 성공률이 향상됩니다.

ONTAP Deploy 2.10부터 내부 네트워크에서 사용하는 MTU 크기를 7,500에서 9,000 사이로 설정할 수 있습니다. 네트워크 연결 검사기를 사용하여 7,500에서 9,000 사이의 MTU 크기를 테스트할 수도 있습니다. 기본 MTU 값은 가상 네트워크 스위치 값으로 설정됩니다. VXLAN과 같은 네트워크 오버레이가 환경에 있는 경우 이 기본값을 더 작은 값으로 변경해야 합니다.



== ONTAP Select

ONTAP Select 외부 네트워크는 클러스터의 모든 아웃바운드 통신을 담당하므로 단일 노드 및 다중 노드 구성 모두에 존재합니다. 이 네트워크는 내부 네트워크처럼 엄격하게 정의된 처리량 요구 사항을 충족하지 않지만, 관리자는 클라이언트와 ONTAP VM 간에 네트워크 병목 현상이 발생하지 않도록 주의해야 합니다. 성능 문제가 ONTAP Select 문제로 잘못 인식될 수 있기 때문입니다.


NOTE: 내부 트래픽과 유사한 방식으로 외부 트래픽은 vSwitch 계층(VST)과 외부 스위치 계층(EST)에서 태그 지정될 수 있습니다. 또한, 외부 트래픽은 VGT라는 프로세스를 통해 ONTAP Select VM 자체에서 태그 지정될 수 있습니다. 섹션을 참조하세요link:concept_nw_data_mgmt_separation.html["데이터 및 관리 트래픽 분리"] 자세한 내용은.

다음 표는 ONTAP Select 내부 및 외부 네트워크 간의 주요 차이점을 강조하여 보여줍니다.

*내부 네트워크와 외부 네트워크 간 빠른 참조*

[cols="3*"]
|===
| 설명 | 내부 네트워크 | 외부 네트워크 


| 네트워크 서비스 | 클러스터 HA/IC RAID SyncMirror (RSM) | 데이터 관리 Intercluster(SnapMirror 및 SnapVault) 


| 네트워크 격리 | 필수의 | 선택 과목 


| 프레임 크기(MTU) | 7,500에서 9,000까지 | 1,500(기본값) 9,000(지원됨) 


| IP 주소 할당 | 자동 생성됨 | 사용자 정의 


| DHCP 지원 | 아니요 | 아니요 
|===


=== NIC 팀 구성

내부 및 외부 네트워크가 고성능과 내결함성을 제공하는 데 필요한 대역폭과 복원력을 모두 갖추도록 하려면 물리적 네트워크 어댑터 팀 구성을 사용하는 것이 좋습니다. 단일 10Gb 링크를 사용하는 2노드 클러스터 구성이 지원됩니다. 하지만 NetApp 권장하는 모범 사례는 ONTAP Select 클러스터의 내부 및 외부 네트워크 모두에서 NIC 팀 구성을 사용하는 것입니다.



=== MAC 주소 생성

모든 ONTAP Select 네트워크 포트에 할당된 MAC 주소는 포함된 배포 유틸리티에 의해 자동으로 생성됩니다. 이 유틸리티는 NetApp 고유 플랫폼별 OUI(Organizational Unique Identifier)를 사용하여 FAS 시스템과의 충돌을 방지합니다. 이 주소의 사본은 ONTAP Select 설치 VM(ONTAP Deploy) 내의 내부 데이터베이스에 저장되어 향후 노드 배포 시 실수로 재할당되는 것을 방지합니다. 관리자는 어떠한 경우에도 네트워크 포트에 할당된 MAC 주소를 수정해서는 안 됩니다.
