---
sidebar: sidebar 
permalink: concept_api_before_workflows.html 
keywords: rest api, deploy rest api, rest, workflows, before you begin 
summary: 워크플로 프로세스를 검토하고 사용할 준비를 해야 합니다. 
---
= ONTAP Select Deploy API 워크플로를 사용하기 전에
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
워크플로 프로세스를 검토하고 사용할 준비를 해야 합니다.



== 워크플로에서 사용되는 API 호출을 이해합니다.

ONTAP Select 온라인 설명서 페이지에는 모든 REST API 호출에 대한 세부 정보가 포함되어 있습니다. 워크플로 샘플에 사용된 각 API 호출에는 여기에서 해당 세부 정보를 반복해서 설명하는 대신, 설명서 페이지에서 해당 호출을 찾는 데 필요한 정보만 포함되어 있습니다. 특정 API 호출을 찾으면 입력 매개변수, 출력 형식, HTTP 상태 코드, 요청 처리 유형을 포함한 호출의 전체 세부 정보를 검토할 수 있습니다.

워크플로 내의 각 API 호출에 대해 다음 정보가 포함되어 있어 설명서 페이지에서 호출을 찾는 데 도움이 됩니다.

* API 호출은 문서 페이지에서 기능적으로 관련된 영역 또는 범주별로 정리되어 있습니다. 특정 API 호출을 찾으려면 페이지 하단으로 스크롤하여 해당 API 범주를 클릭하세요.
* HTTP 동사 HTTP 동사는 리소스에서 수행되는 동작을 식별합니다. 각 API 호출은 단일 HTTP 동사를 통해 실행됩니다.
* 경로 경로는 호출 수행 시 작업이 적용되는 특정 리소스를 결정합니다. 경로 문자열은 핵심 URL에 추가되어 리소스를 식별하는 완전한 URL을 형성합니다.




== REST API에 직접 액세스하기 위한 URL을 구성합니다.

ONTAP Select 문서 페이지 외에도 Python과 같은 프로그래밍 언어를 통해 Deploy REST API에 직접 액세스할 수 있습니다. 이 경우, 핵심 URL은 온라인 문서 페이지에 액세스할 때 사용하는 URL과 약간 다릅니다. API에 직접 액세스할 때는 도메인 및 포트 문자열에 /api를 추가해야 합니다. 예를 들어:
`\http://deploy.mycompany.com/api`
