---
sidebar: sidebar 
permalink: concept_lic_evaluation.html 
keywords: license, licensing, evaluation, upgrade license 
summary: 구매를 결정하기 전에 ONTAP Select 평가해 보려면 평가판 라이선스를 사용할 수 있습니다. 평가판 라이선스는 ONTAP Select Deploy 관리 유틸리티에 포함되어 있으며, 평가판 배포의 일부로 각 ONTAP Select 노드에 자동으로 적용됩니다. 
---
= ONTAP Select 배포를 위한 평가 라이선스
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 평가판 라이선스 또는 구매한 라이선스로 배포할 수 있습니다. 선택한 라이선스는 ONTAP Select 클러스터의 각 노드에 적용되어야 하며, 따라서 전체 클러스터에 적용됩니다. 구매를 결정하기 전에 ONTAP Select 평가해 보려면 평가판 라이선스를 사용할 수 있습니다. 평가판 라이선스는 ONTAP Select Deploy 관리 유틸리티에 포함되어 있으며, 평가판 배포의 일부로 각 ONTAP Select 노드에 자동으로 적용됩니다.

[NOTE]
====
ONTAP Select Deploy 관리 유틸리티를 다운로드하려면 다음이 필요합니다.

* 등록된 NetApp 지원 사이트 계정. 계정이 없으면 다음을 참조하세요. https://mysupport.netapp.com/site/user/registration["사용자 등록"^] .
* 에게 https://mysupport.netapp.com/site/downloads/evaluation/ontap-select["최종 사용자 라이선스 계약에 동의하세요"^] 평가 라이선스를 사용하여 ONTAP Select 배포를 위한 것입니다.


====
평가 클러스터를 배포하고 지원할 때는 다음과 같은 몇 가지 사항을 고려해야 합니다.

* 클러스터는 평가 목적으로만 사용할 수 있습니다. 평가 라이선스가 있는 클러스터를 프로덕션 환경에서 사용해서는 안 됩니다.
* 각 호스트를 구성할 때 다음과 같이 ONTAP Select Deploy 관리 유틸리티를 사용해야 합니다.
+
** 일련번호를 제공하지 마세요
** 평가판 라이선스를 사용하도록 구성






== 라이센스 특성

ONTAP Select 평가 라이선스는 다음과 같은 특징을 가지고 있습니다.

* 저장 용량이 있는 프로덕션 라이선스는 필요하지 않습니다.
* 노드 일련 번호는 20자리이며 ONTAP Select Deploy에서 자동으로 생성됩니다.
+
( NetApp 에서 직접 구매하지 않음)

* 라이센스에서 제공하는 평가 기간은 최대 90일까지 가능합니다.
* 각 노드에 할당된 최대 저장 용량은 프로덕션 라이선스와 동일합니다.




== 프로덕션 라이선스로 업그레이드

ONTAP Select 평가판 클러스터를 업그레이드하여 프로덕션 라이선스를 사용할 수 있습니다. 다음 제한 사항을 숙지해야 합니다.

* 라이선스 업그레이드를 수행하려면 Deploy 관리 유틸리티를 사용해야 합니다.
* 용량 계층 라이선스를 사용할 수 있지만 용량 풀 라이선스는 지원되지 않습니다.
* 각 노드에는 클러스터 크기에 따라 프로덕션 라이선스에 필요한 최소 요구 사항을 지원하기에 충분한 저장 공간이 할당되어야 합니다.


보다link:task_adm_licenses.html["평가판 라이선스를 프로덕션 라이선스로 변환"] 자세한 내용은.

.관련 정보
* link:concept_lic_production.html["프로덕션 배포를 위한 라이선스에 대해 알아보세요"]
* link:deploy-evaluation-ontap-select-ovf-template.html["ONTAP Select 클러스터의 90일 평가 인스턴스 배포"]

