---
sidebar: sidebar 
permalink: concept_nw_concepts_chars.html 
keywords: ontap select, networking concepts, cluster characteristics 
summary: 먼저 ONTAP Select 환경에 적용되는 일반적인 네트워킹 개념을 숙지하십시오. 그런 다음 단일 노드 및 다중 노드 클러스터에서 사용 가능한 특정 특성과 옵션을 살펴보십시오. 
---
= ONTAP Select 네트워킹 개념 및 특성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
먼저 ONTAP Select 환경에 적용되는 일반적인 네트워킹 개념을 숙지하십시오. 그런 다음 단일 노드 및 다중 노드 클러스터에서 사용 가능한 특정 특성과 옵션을 살펴보십시오.



== 물리적 네트워킹

물리적 네트워크는 주로 기반 2계층 스위칭 인프라를 제공함으로써 ONTAP Select 클러스터 구축을 지원합니다. 물리적 네트워크와 관련된 구성에는 하이퍼바이저 호스트와 더 광범위한 스위치드 네트워크 환경이 모두 포함됩니다.



=== 호스트 NIC 옵션

각 ONTAP Select 하이퍼바이저 호스트는 2개 또는 4개의 물리적 포트로 구성되어야 합니다. 선택하는 정확한 구성은 다음을 포함한 여러 요인에 따라 달라집니다.

* 클러스터에 ONTAP Select 호스트가 하나 또는 여러 개 포함되어 있는지 여부
* 어떤 하이퍼바이저 운영 체제가 사용됩니까?
* 가상 스위치가 구성되는 방식
* LACP가 링크와 함께 사용되는지 여부




=== 물리적 스위치 구성

물리적 스위치 구성이 ONTAP Select 배포를 지원하는지 확인해야 합니다. 물리적 스위치는 하이퍼바이저 기반 가상 스위치와 통합되어 있습니다. 어떤 구성을 선택할지는 여러 요인에 따라 달라집니다. 주요 고려 사항은 다음과 같습니다.

* 내부 네트워크와 외부 네트워크를 어떻게 분리할 것인가?
* 데이터 네트워크와 관리 네트워크를 분리할 예정인가요?
* 2계층 VLAN은 어떻게 구성되나요?




== 논리적 네트워킹

ONTAP Select 두 개의 서로 다른 논리적 네트워크를 사용하여 트래픽을 유형에 따라 구분합니다. 특히, 트래픽은 클러스터 내의 호스트 간뿐만 아니라 클러스터 외부의 스토리지 클라이언트 및 다른 머신으로 이동할 수 있습니다. 하이퍼바이저가 관리하는 가상 스위치는 논리적 네트워크를 지원합니다.



=== 내부 네트워크

다중 노드 클러스터 배포 시, 각 ONTAP Select 노드는 격리된 "내부" 네트워크를 사용하여 통신합니다. 이 네트워크는 ONTAP Select 클러스터의 노드 외부에 노출되거나 사용할 수 없습니다.


NOTE: 내부 네트워크는 다중 노드 클러스터에만 존재합니다.

내부 네트워크는 다음과 같은 특징을 가지고 있습니다.

* 다음을 포함한 ONTAP 클러스터 내 트래픽을 처리하는 데 사용됩니다.
+
** 무리
** 고가용성 상호 연결(HA-IC)
** RAID 동기화 미러(RSM)


* VLAN 기반 단일 계층 2 네트워크
* 정적 IP 주소는 ONTAP Select 에 의해 할당됩니다.
+
** IPv4만
** DHCP를 사용하지 않음
** 링크 로컬 주소


* MTU 크기는 기본적으로 9000바이트이며 7500-9000 범위 내에서 조정 가능합니다.




=== 외부 네트워크

외부 네트워크는 ONTAP Select 클러스터 노드와 외부 스토리지 클라이언트 및 다른 머신 간의 트래픽을 처리합니다. 외부 네트워크는 모든 클러스터 배포의 일부이며 다음과 같은 특징을 갖습니다.

* 다음을 포함한 ONTAP 트래픽을 처리하는 데 사용됩니다.
+
** 데이터(NFS, CIFS, iSCSI)
** 관리(클러스터 및 노드, 선택적으로 SVM)
** 클러스터 간(선택 사항)


* 선택적으로 VLAN을 지원합니다.
+
** 데이터 포트 그룹
** 관리 포트 그룹


* 관리자의 구성 선택에 따라 할당되는 IP 주소:
+
** IPv4 또는 IPv6


* MTU 크기는 기본적으로 1500바이트입니다(조정 가능)


외부 네트워크에는 모든 규모의 클러스터가 존재합니다.



== 가상 머신 네트워킹 환경

하이퍼바이저 호스트는 여러 가지 네트워킹 기능을 제공합니다.

ONTAP Select 가상 머신을 통해 노출되는 다음 기능을 사용합니다.

가상 머신 포트:: ONTAP Select 에서 사용할 수 있는 포트는 여러 개입니다. 포트는 클러스터 크기를 포함한 여러 요인에 따라 할당되고 사용됩니다.
가상 스위치:: 하이퍼바이저 환경 내의 가상 스위치 소프트웨어(vSwitch(VMware) 또는 Open vSwitch(KVM))는 가상 머신에서 노출된 포트를 물리적 이더넷 NIC 포트와 연결합니다. 환경에 맞게 모든 ONTAP Select 호스트에 대해 vSwitch를 구성해야 합니다.

