---
sidebar: sidebar 
permalink: concept_adm_upgrading_nodes.html 
keywords: administer, administering, web, upgrading nodes 
summary: ONTAP Select 클러스터를 배포한 후에는 표준 ONTAP 소프트웨어 업그레이드 절차를 사용하여 필요에 따라 각 노드의 ONTAP 이미지를 업그레이드할 수 있습니다. 
---
= ONTAP Select 노드 업그레이드
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 클러스터를 배포한 후 필요에 따라 클러스터의 각 노드에서 ONTAP 이미지를 업그레이드할 수 있습니다.


CAUTION: Deploy 관리 유틸리티를 사용하여 기존 ONTAP Select 노드를 업그레이드할 수 없습니다. Deploy 유틸리티는 새 ONTAP Select 클러스터를 생성하는 데만 사용할 수 있습니다.



== 일반 절차

높은 수준에서는 다음 단계에 따라 기존 ONTAP Select 노드를 업그레이드해야 합니다.

. NetApp 지원 사이트의 다운로드 페이지로 이동합니다.
+
https://mysupport.netapp.com/site/downloads["NetApp 지원 다운로드"^]

. * ONTAP Select Node Upgrade*를 클릭합니다.
. 필요에 따라 모든 프롬프트에 응답하여 적절한 업그레이드 이미지를 선택하고 다운로드합니다.
+
ONTAP Select 노드를 업그레이드하기 전에 릴리스 노트에서 추가 정보와 필요한 절차를 검토하세요.

. ONTAP Select 업그레이드 파일을 사용하여 표준 ONTAP 업그레이드 절차를 사용하여 ONTAP Select 노드를 업그레이드하십시오. 지원되는 업그레이드 경로에 대한 정보는 다음을 참조하세요.link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html["지원되는 ONTAP 업그레이드 경로"^] .




== ONTAP Select 노드 되돌리기

ONTAP Select 노드를 원래 설치된 버전보다 이전 버전으로 되돌릴 수 없습니다. 예를 들어:

ONTAP Select 9.16.1이 처음 설치되었습니다.:: 필요한 경우 노드를 버전 9.17.1로 업그레이드한 다음 버전 9.16.1로 되돌릴 수 있습니다.
ONTAP Select 9.17.1이 처음 설치되었습니다.:: 이전에 설치된 버전이 없기 때문에 되돌릴 수 없습니다.




== VMXNET3 네트워크 드라이버를 사용하세요

VMXNET3는 VMware ESXi의 새 클러스터 배포에 포함된 기본 네트워크 드라이버입니다. ONTAP Select 9.4 이하 버전을 실행하는 기존 ONTAP Select 노드를 업그레이드하는 경우 네트워크 드라이버가 자동으로 업그레이드되지 않습니다. VMXNET3으로 수동으로 업그레이드해야 합니다. 업그레이드 관련 지원은 NetApp 지원팀에 문의하십시오.

.관련 정보
link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["ONTAP 업그레이드 개요"^]
