---
sidebar: sidebar 
permalink: concept_terminology.html 
keywords: terminology, key concepts, concepts 
summary: ONTAP Select 탐색하고 배포를 계획하기 시작할 때 먼저 용어와 핵심 개념에 익숙해지는 것이 좋습니다. 
---
= ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 탐색하고 배포를 계획하기 시작할 때 먼저 용어와 핵심 개념에 익숙해지는 것이 좋습니다.

ONTAP Select 배포:: ONTAP Select Deploy는 ONTAP Select 클러스터를 배포하는 데 사용하는 관리 유틸리티입니다. Deploy 유틸리티는 전용 Linux 가상 머신에서 실행됩니다. 웹 사용자 인터페이스, CLI 관리 셸 및 REST API를 통해 Deploy 유틸리티에 액세스할 수 있습니다.
커널 기반 가상 머신:: 커널 기반 가상 머신(KVM)은 Linux 커널의 가상화 기능으로, Linux 커널을 하이퍼바이저 플랫폼으로 사용할 수 있도록 합니다. 다양한 게스트 운영 체제가 지원됩니다.
하이퍼바이저 호스트 대 ONTAP Select 노드:: _하이퍼바이저 호스트_는 ONTAP Select 가상 머신을 호스팅하는 핵심 하드웨어 플랫폼입니다. ONTAP Select 가상 머신이 하이퍼바이저 호스트에 배포되고 활성화되면 _ONTAP Select 노드_로 간주됩니다.
ONTAP Select:: 1개, 2개, 4개, 6개 또는 8개의 노드로 구성된 _ONTAP Select 클러스터_를 생성할 수 있습니다. 다중 노드 클러스터는 항상 하나 이상의 HA 쌍을 포함합니다. 예를 들어, 4노드 클러스터는 2개의 HA 쌍으로 구성됩니다. 단일 노드 클러스터는 HA 기능을 제공하지 않습니다.
하이퍼바이저 호스트 환경 준비:: Deploy 관리 유틸리티를 사용하여 ONTAP Select 클러스터를 배포하기 전에 ONTAP Select 실행될 하이퍼바이저 호스트(스토리지 및 네트워킹 환경 포함)를 준비해야 합니다. 이 호스트 사전 구성은 현재 요구 사항 및 제한 사항을 기반으로 ONTAP Select 제품 외부에서 수행됩니다.
평가 배포 대 프로덕션 배포:: 모든 ONTAP Select 노드는 _평가판 라이선스_ 또는 _구매 라이선스_로 실행됩니다. 평가 라이선스를 사용하면 ONTAP Select 프로덕션 환경에 배포하기 전에 평가해 볼 수 있습니다. 평가 라이선스는 자동으로 생성되어 적용됩니다. 프로덕션 환경에 클러스터를 배포하는 경우 다음을 선택하는 라이선스를 구매해야 합니다.
+
--
* 라이선싱 모델
* 저장 용량
* 플랫폼 라이선스 제공


--
용량 계층 라이선싱 모델:: 용량 계층(Capacity Tiers) 라이선싱 모델은 ONTAP Select 배포를 위한 스토리지 라이선싱 시 사용되는 기본 옵션입니다. NetApp AFF 및 FAS 에 사용되는 ONTAP 모델을 기반으로 합니다. 각 노드에는 별도의 라이선스가 필요합니다. 스토리지 용량은 노드에 고정되며 영구적으로 사용 가능하므로 갱신이 필요하지 않습니다.
용량 풀 라이선싱 모델:: 용량 풀 라이선스 모델은 Deploy 2.10을 사용하는 ONTAP Select 9.5에서 도입되었습니다. 각 스토리지 용량 풀에는 별도의 라이선스가 필요합니다. 용량 풀 라이선스는 라이선스 관리자 인스턴스(즉, Deploy 인스턴스)에 고정되며 구매 약관에 따라 갱신해야 합니다. 조직 내에서 원하는 수의 용량 풀에 라이선스를 부여하고 사용할 수 있습니다. 하지만 용량 풀은 ONTAP Select 노드에서 공유되므로 일반적으로 용량 계층 라이선스보다 필요한 라이선스 수가 적습니다.
라이선스 관리자:: 라이선스 관리자는 용량 풀 라이선싱을 지원하는 소프트웨어 구성 요소입니다. 현재 Deploy 관리 유틸리티의 일부입니다. LM은 관리하는 공유 풀에서 ONTAP Select 노드에 스토리지를 임대합니다. _라이선스 잠금 ID_는 각 LM 인스턴스와 각 Deploy 인스턴스를 고유하게 식별하는 숫자 문자열입니다. 라이선스 파일을 생성하려면 용량 풀 라이선스 일련 번호와 LLID를 모두 사용해야 합니다.
플랫폼 라이선스 제공:: 라이선스를 구매할 때 ONTAP Select 가상 머신의 크기 및 기능을 결정하는 세 가지 라이선스 제공이 있습니다.
+
--
* 기준
* 프리미엄
* 프리미엄 XL


--


자세한 내용은 _계획_ 및 _라이선스_ 두 섹션을 참조하세요.

스토리지 풀과 데이터 저장소:: ONTAP Select 스토리지 풀은 기본 물리적 스토리지를 추상화하고 숨기도록 설계된 논리적 데이터 컨테이너입니다. 스토리지 풀은 하이퍼바이저에 독립적입니다. ESXi 하이퍼바이저 호스트에 배포될 경우 ONTAP Select 스토리지 풀은 VMware 데이터 저장소와 동일합니다.
클러스터 MTU:: 클러스터 MTU는 ONTAP Select 다중 노드 클러스터에 사용되는 내부 네트워크의 MTU 크기를 구성할 수 있는 기능입니다. Deploy 관리 유틸리티는 HA 쌍을 구성할 때 네트워킹 환경에 맞게 MTU 크기를 조정합니다. 값을 수동으로 설정할 수도 있습니다.
ONTAP Select vNAS:: ONTAP Select vNAS 솔루션을 사용하면 ONTAP Select 노드가 외부 스토리지의 VMware 데이터스토어에 액세스할 수 있습니다. ONTAP Select vNAS를 사용하면 로컬 RAID 컨트롤러가 더 이상 필요하지 않으며, RAID 기능은 원격 스토리지에서 제공되는 것으로 간주됩니다. ONTAP Select vNAS는 다음과 같은 방법으로 구성할 수 있습니다.
+
--
* VMware vSAN
* 일반 외부 스토리지 어레이


--


두 경우 모두 ONTAP Select 클러스터를 생성하거나 기존 노드의 저장 용량을 확장하기 전에 외부 저장소를 구성해야 합니다.

ESXi VM에서 노드 재호스팅:: ONTAP Select vNAS 솔루션(VMware vSAN 또는 일반 외부 스토리지 어레이)을 통해 제공되는 외부 스토리지를 사용하는 클러스터를 배포하는 경우 ONTAP Select 노드를 호스팅하는 ESXi 가상 머신은 다음 VMware 기능을 활용하는 작업을 통해 이동할 수 있습니다.
+
--
* v모션
* 고가용성(HA)
* 분산 리소스 스케줄러(DRS)
+
ONTAP Select Deploy 유틸리티는 다음과 같은 클러스터에서 작업을 실행하는 과정에서 가상 머신의 이동을 감지합니다.

* 클러스터 온라인
* 클러스터 오프라인
* 저장 공간 추가
+
가상 머신이 이동되면 Deploy 유틸리티는 내부 데이터베이스를 업데이트하고 새 ESXi 호스트를 구성합니다. ONTAP Select 노드에서 수행되는 모든 작업은 가상 머신 이동 및 Deploy 업데이트가 완료될 때까지 차단됩니다.



--
KVM용 Open vSwitch:: Open vSwitch(OVS)는 여러 네트워킹 프로토콜을 지원하는 가상 스위치의 소프트웨어 구현입니다. OVS는 오픈 소스이며 Apache 라이선스 2.0에 따라 제공됩니다.
중재 서비스:: ONTAP Select Deploy 유틸리티에는 활성 2노드 클러스터의 노드에 연결하는 중재자 서비스가 포함되어 있습니다. 이 서비스는 각 HA 쌍을 모니터링하고 장애 관리를 지원합니다.



CAUTION: 활성 2노드 클러스터가 하나 이상 있는 경우, 클러스터를 관리하는 ONTAP Select Deploy 가상 머신이 항상 실행 중이어야 합니다. Deploy 가상 머신이 중지되면 Mediator 서비스를 사용할 수 없으며 2노드 클러스터의 HA 기능이 손실됩니다.

MetroCluster SDS:: MetroCluster SDS는 2노드 ONTAP Select 클러스터를 구축할 때 추가 구성 옵션을 제공하는 기능입니다. 일반적인 2노드 ROBO 구축과 달리 MetroCluster SDS 노드는 훨씬 더 먼 거리로 분리될 수 있습니다. 이러한 물리적 분리를 통해 재해 복구와 같은 추가 활용 사례가 가능합니다. MetroCluster SDS를 사용하려면 프리미엄 라이선스 이상이 필요합니다. 또한, 노드 간 네트워크는 최소 지연 시간 요건을 지원해야 합니다.
자격 증명 저장소:: 배포 자격 증명 저장소는 계정 자격 증명을 보관하는 보안 데이터베이스입니다. 주로 새 클러스터를 생성하는 과정에서 하이퍼바이저 호스트를 등록하는 데 사용됩니다. 자세한 내용은 _계획_ 섹션을 참조하십시오.
스토리지 효율성:: ONTAP Select FAS 및 AFF 어레이에 있는 스토리지 효율성 옵션과 유사한 스토리지 효율성 옵션을 제공합니다. 개념적으로, 프리미엄 라이선스를 사용하는 DAS(직접 연결 스토리지) SSD를 사용하는 ONTAP Select AFF 어레이와 유사합니다. HDD를 사용하는 DAS 구성 및 모든 vNAS 구성은 FAS 어레이와 유사한 것으로 간주해야 합니다. 두 구성의 주요 차이점은 DAS SSD를 사용하는 ONTAP Select 인라인 집계 수준 중복 제거와 집계 수준 백그라운드 중복 제거를 지원한다는 것입니다. 나머지 스토리지 효율성 옵션은 두 구성 모두에서 사용할 수 있습니다.
+
--
vNAS 기본 구성은 단일 인스턴스 데이터 로깅(SIDL)이라는 쓰기 최적화 기능을 활성화합니다. ONTAP Select 9.6 이상 릴리스에서는 SIDL을 활성화하면 백그라운드 ONTAP 스토리지 효율성 기능이 검증됩니다. 자세한 내용은 _심층 분석_ 섹션을 참조하십시오.

--
클러스터 새로 고침:: 클러스터를 생성한 후에는 ONTAP 또는 하이퍼바이저 관리 도구를 사용하여 Deploy 유틸리티 외부에서 클러스터 또는 가상 머신 구성을 변경할 수 있습니다. 구성 변경을 유발하는 가상 머신을 마이그레이션할 수도 있습니다. 이러한 변경 사항이 발생하면 Deploy 유틸리티가 자동으로 업데이트되지 않아 클러스터 상태와 동기화되지 않을 수 있습니다. 클러스터 새로 고침 기능을 사용하여 Deploy 구성 데이터베이스를 업데이트할 수 있습니다. 클러스터 새로 고침은 Deploy 웹 사용자 인터페이스, CLI 관리 셸 및 REST API를 통해 사용할 수 있습니다.
소프트웨어 RAID:: DAS(직접 연결 스토리지)를 사용할 때 RAID 기능은 일반적으로 로컬 하드웨어 RAID 컨트롤러를 통해 제공됩니다. 하지만 ONTAP Select 노드가 RAID 기능을 제공하는 경우, 소프트웨어 RAID를 사용하도록 노드를 구성할 수 있습니다. 소프트웨어 RAID를 사용하면 하드웨어 RAID 컨트롤러가 더 이상 필요하지 않습니다.


[[ontap-select-image-install]]
ONTAP Select 설치:: Deploy 관리 유틸리티에는 ONTAP Select 의 단일 버전만 포함되어 있습니다. 포함된 버전은 출시 시점을 기준으로 사용 가능한 최신 버전입니다. ONTAP Select 이미지 설치 기능을 사용하면 Deploy 유틸리티 인스턴스에 이전 버전의 ONTAP Select 추가하여 ONTAP Select 클러스터를 배포할 때 사용할 수 있습니다. 보다link:task_cli_deploy_image_add.html["ONTAP Select 자세한 정보를 확인하세요."] .



NOTE: Deploy 인스턴스에 포함된 원래 버전보다 이전 버전의 ONTAP Select 이미지만 추가해야 합니다. Deploy를 업데이트하지 않고 이후 버전의 ONTAP Select 추가하는 것은 지원되지 않습니다.

ONTAP Select 클러스터 배포 후 관리:: ONTAP Select 클러스터를 배포한 후에는 하드웨어 기반 ONTAP 클러스터와 마찬가지로 클러스터를 구성할 수 있습니다. 예를 들어, System Manager 또는 표준 ONTAP 명령줄 인터페이스를 사용하여 ONTAP Select 클러스터를 구성할 수 있습니다.


.관련 정보
link:task_cli_deploy_image_add.html["배포할 ONTAP Select 이미지 추가"]
