---
sidebar: sidebar 
permalink: concept_lic_cp_restrictions.html 
keywords: license, licensing, Capacity Pools, restrictions 
summary: 용량 풀 라이선스 모델을 사용할 때 적용되는 제한 사항은 아래와 같습니다. 
---
= ONTAP Select Capacity Pools 라이선싱에 대한 배포 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
용량 풀 라이선스 모델을 사용할 때 적용되는 제한 사항은 아래와 같습니다.

.클러스터별 일관된 라이선싱 모델
단일 ONTAP Select 클러스터 내의 모든 노드는 동일한 라이선스 모델(용량 계층 또는 용량 풀)을 사용해야 합니다. 단일 클러스터 내의 노드에 대해 라이선스 유형을 혼합할 수 없습니다.

.클러스터의 모든 노드는 동일한 License Manager 인스턴스를 사용합니다.
ONTAP Select 클러스터에서 용량 풀 라이선스가 있는 모든 노드는 동일한 License Manager 인스턴스를 사용해야 합니다. 각 Deploy 인스턴스 내에 License Manager 인스턴스가 하나씩 있으므로, 이 제한은 클러스터의 모든 노드가 동일한 Deploy 인스턴스로 관리되어야 한다는 기존 요구 사항을 다시 명시한 것입니다.

.노드당 하나의 용량 풀
각 노드는 정확히 하나의 용량 풀에서 스토리지를 임대할 수 있습니다. 노드는 두 개 이상의 풀을 사용할 수 없습니다.

.HA 쌍의 노드에 대한 동일한 풀
단일 HA 쌍에 속한 두 노드는 모두 동일한 용량 풀에서 스토리지를 임대해야 합니다. 그러나 동일 클러스터 내의 서로 다른 HA 쌍은 동일한 라이선스 관리자가 관리하는 서로 다른 풀에서 스토리지를 임대할 수 있습니다.

.저장 라이센스 기간
NetApp 에서 스토리지 라이선스를 구매할 때 라이선스 기간을 선택해야 합니다. 예를 들어, 라이선스 유효 기간은 1년일 수 있습니다.

.데이터 집계 임대 기간
ONTAP Select 노드가 데이터 집계를 위한 스토리지 임대를 요청하면 License Manager는 용량 풀 구성에 따라 특정 기간 동안 임대를 제공합니다. 각 풀의 임대 기간은 1시간에서 7일 사이로 설정할 수 있습니다. 기본 임대 기간은 24시간입니다.

.Deploy에 할당된 정적 IP 주소
용량 풀 라이선싱을 사용하는 경우 배포 관리 유틸리티에 고정 IP 주소를 할당해야 합니다.
