---
sidebar: sidebar 
permalink: concept_api_operation.html 
keywords: rest api, deploy rest api, rest, operation, basic operation 
summary: REST는 공통된 기술과 모범 사례를 제공하지만, 각 API의 세부 사항은 설계 방식에 따라 달라질 수 있습니다. ONTAP Select Deploy API를 사용하기 전에 해당 API의 세부 사항과 운영 특성을 숙지해야 합니다. 
---
= ONTAP Select Deploy API 기본 운영 특성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
REST는 공통된 기술과 모범 사례를 제공하지만, 각 API의 세부 사항은 설계 방식에 따라 달라질 수 있습니다. ONTAP Select Deploy API를 사용하기 전에 해당 API의 세부 사항과 운영 특성을 숙지해야 합니다.



== 하이퍼바이저 호스트 대 ONTAP Select 노드

_하이퍼바이저 호스트_는 ONTAP Select 가상 머신을 호스팅하는 핵심 하드웨어 플랫폼입니다. ONTAP Select 가상 머신이 하이퍼바이저 호스트에 배포되고 활성화되면 해당 가상 머신은 _ONTAP Select 노드_로 간주됩니다. Deploy REST API 버전 3에서는 호스트 객체와 노드 객체가 분리되어 있습니다. 이를 통해 하나 이상의 ONTAP Select 노드가 동일한 하이퍼바이저 호스트에서 실행될 수 있는 일대다 관계가 가능합니다.



== 객체 식별자

각 리소스 인스턴스 또는 객체는 생성될 때 고유 식별자가 할당됩니다. 이러한 식별자는 ONTAP Select Deploy의 특정 인스턴스 내에서 전역적으로 고유합니다. 새로운 객체 인스턴스를 생성하는 API 호출을 발행한 후 연관된 ID 값이 호출자에게 반환됩니다. `location` HTTP 응답의 헤더. 식별자를 추출하여 리소스 인스턴스를 참조할 때 후속 호출에서 사용할 수 있습니다.


NOTE: 객체 식별자의 내용과 내부 구조는 언제든지 변경될 수 있습니다. 연관된 객체를 참조할 때 해당 API 호출에서 필요에 따라서만 식별자를 사용해야 합니다.



== 요청 식별자

모든 성공적인 API 요청에는 고유 식별자가 할당됩니다. 식별자는 다음에서 반환됩니다. `request-id` 연관된 HTTP 응답의 헤더. 요청 식별자를 사용하여 단일 특정 API 요청-응답 트랜잭션의 활동을 집합적으로 참조할 수 있습니다. 예를 들어, 요청 ID를 기반으로 트랜잭션의 모든 이벤트 메시지를 검색할 수 있습니다.



== 동기 및 비동기 호출

서버가 클라이언트로부터 받은 HTTP 요청을 처리하는 주요 방법은 두 가지가 있습니다.

* 동기식 서버는 요청을 즉시 수행하고 200, 201 또는 204 상태 코드로 응답합니다.
* 비동기: 서버가 요청을 수락하고 상태 코드 202로 응답합니다. 이는 서버가 클라이언트 요청을 수락하고 요청을 완료하기 위한 백그라운드 작업을 시작했음을 나타냅니다. 최종 성공 또는 실패 여부는 즉시 알 수 없으며 추가 API 호출을 통해 결정해야 합니다.




== 장기 실행 작업의 완료 확인

일반적으로 완료하는 데 시간이 오래 걸릴 수 있는 모든 작업은 서버에서 백그라운드 작업을 사용하여 비동기적으로 처리됩니다. Deploy REST API를 사용하면 모든 백그라운드 작업은 작업을 추적하고 현재 상태와 같은 정보를 제공하는 Job 객체에 의해 고정됩니다. 백그라운드 작업이 생성된 후 고유 식별자를 포함한 Job 객체가 HTTP 응답으로 반환됩니다.

Job 객체를 직접 쿼리하여 관련 API 호출의 성공 또는 실패 여부를 확인할 수 있습니다. 자세한 내용은 _Job 객체를 사용한 비동기 처리_를 참조하세요.

Job 객체를 사용하는 것 외에도 요청의 성공 또는 실패를 판별하는 데 사용할 수 있는 다른 방법이 있습니다.

* 이벤트 메시지: 원래 응답과 함께 반환된 요청 ID를 사용하여 특정 API 호출과 관련된 모든 이벤트 메시지를 검색할 수 있습니다. 이벤트 메시지에는 일반적으로 성공 또는 실패 여부가 표시되며, 오류 조건을 디버깅할 때도 유용할 수 있습니다.
* 리소스 상태 또는 상태 여러 리소스는 요청의 성공 또는 실패를 간접적으로 확인하기 위해 쿼리할 수 있는 상태 또는 상태 값을 유지합니다.




== 보안

Deploy API는 다음과 같은 보안 기술을 사용합니다.

* 전송 계층 보안: 배포 서버와 클라이언트 간에 네트워크를 통해 전송되는 모든 트래픽은 TLS를 통해 암호화됩니다. 암호화되지 않은 채널을 통한 HTTP 프로토콜 사용은 지원되지 않습니다. TLS 버전 1.2가 지원됩니다.
* HTTP 인증: 기본 인증은 모든 API 트랜잭션에 사용됩니다. 사용자 이름과 비밀번호를 base64 문자열로 포함하는 HTTP 헤더가 모든 요청에 추가됩니다.

