---
sidebar: sidebar 
permalink: concept_adm_before.html 
keywords: administer, administering, web, before you begin 
summary: ONTAP Select 클러스터를 생성한 후에는 다양한 관리 작업을 수행하여 배포를 지원할 수 있습니다. 몇 가지 일반적인 고려 사항이 있습니다. 
---
= ONTAP Select 관리를 시작하기 전에
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 클러스터를 생성한 후에는 다양한 관리 작업을 수행하여 배포를 지원할 수 있습니다. 몇 가지 일반적인 고려 사항이 있습니다.

일반적으로 Deploy 웹 인터페이스를 사용하여 수행할 수 있는 절차는 세 가지 범주 중 하나에 속합니다.

.ONTAP Select 클러스터 배포
단일 노드 또는 다중 노드 클러스터를 배포할 수 있습니다. 보다link:task_deploy_cluster.html["ONTAP Select 클러스터 배포"] 자세한 내용은.

.기존 ONTAP Select 클러스터로 프로시저 수행
관리 절차는 _보안_ 및 _클러스터_와 같은 다양한 범주로 구성됩니다.

.배포 유틸리티에서 절차를 수행합니다.
배포에는 몇 가지 특정 절차가 있습니다(예: 관리자 비밀번호 변경).



== ONTAP Select 관리

ONTAP Select 지원에는 다양한 관리 절차가 있습니다. 또한 Deploy 관리 유틸리티에만 적용되는 절차도 있습니다. 이러한 절차 중 가장 중요한 절차는 다음과 같습니다. 일반적으로 모든 절차는 Deploy 웹 사용자 인터페이스를 사용합니다.


NOTE: 당신도 할 수 있습니다link:https://docs.netapp.com/us-en/ontap-select/task_cli_signing_in.html["명령줄 인터페이스를 사용하세요"] ONTAP Select 관리합니다.



== 추가 ONTAP 구성 수행

ONTAP Select 클러스터가 배포된 후에는 하드웨어 기반 ONTAP 시스템과 마찬가지로 클러스터를 구성하고 관리할 수 있습니다. 예를 들어 ONTAP System Manager 또는 ONTAP CLI를 사용하여 ONTAP Select 클러스터를 구성할 수 있습니다.

.NetApp 클라이언트 소프트웨어
다음의 지원되는 NetApp 클라이언트 소프트웨어를 사용하여 ONTAP Select 에 연결할 수 있습니다.

* ONTAP 시스템 관리자
* Active IQ Unified Manager
* OnCommand Insight
* OnCommand Workflow Automation
* SnapCenter
* VMware vSphere용 가상 스토리지 콘솔


지원되는 클라이언트 소프트웨어 버전을 확인하려면 다음을 검토하세요.link:https://mysupport.netapp.com/matrix/["상호 운용성 매트릭스 도구"^] . ONTAP 버전이 ONTAP Select 에서도 지원됩니다.


NOTE: SnapCenter 및 해당 플러그인을 사용하려면 서버 기반 라이선스가 필요합니다. ONTAP Select 에서는 현재 SnapCenter 플러그인의 스토리지 시스템 라이선스가 지원되지 않습니다.

목록에 포함되지 않은 다른 NetApp 클라이언트 소프트웨어는 ONTAP Select 에서 지원되지 않습니다.

.가능한 구성 옵션
클러스터를 구성할 때 사용할 수 있는 옵션은 다음과 같습니다.

* 네트워킹 구성 만들기
* 집계 배치
* 데이터 저장 VM(SVM) 생성


.저장 용량이 있는 라이센스 구매
ONTAP Select 클러스터를 배포하는 과정에서 저장 용량이 있는 라이선스 파일을 설치하지 않기로 결정한 경우, 구매한 라이선스로 실행되는 클러스터의 유예 기간이 만료되기 전에 라이선스 파일을 획득하여 설치해야 합니다.

.미러링된 집계
Deploy 관리 유틸리티는 사용 가능한 데이터 저장소 공간(예: Pool0 및 Pool1)에서 각 ONTAP Select 노드에 데이터 예비 디스크를 생성합니다. 다중 노드 클러스터에서 데이터의 고가용성을 구현하려면 이러한 예비 디스크를 사용하여 미러링된 집계를 생성해야 합니다.


NOTE: 고가용성 인수는 데이터 집계가 미러링된 집계로 구성된 경우에만 지원됩니다.
