---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, Capacity Pools, operation details 
summary: 용량 풀 라이선싱 모델은 용량 계층 모델과 다릅니다. 각 노드에 전용 스토리지 용량을 할당하는 대신, 스토리지 용량을 풀에 할당하여 여러 노드에서 공유합니다. 용량 풀 모델을 지원하기 위해 추가 구성 요소와 프로세스가 개발되었습니다. 
---
= ONTAP Select Capacity Pools 라이선싱 모델에 대한 운영 세부 정보
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
용량 풀 라이선싱 모델은 용량 계층 모델과 다릅니다. 각 노드에 전용 스토리지 용량을 할당하는 대신, 스토리지 용량을 풀에 할당하여 여러 노드에서 공유합니다. 용량 풀 모델을 지원하기 위해 추가 구성 요소와 프로세스가 개발되었습니다.



== 라이선스 관리자

라이선스 관리자는 배포 관리 유틸리티의 각 인스턴스 내에서 별도의 프로세스로 실행됩니다. LM이 제공하는 기능은 다음과 같습니다.

* 용량 풀 라이선스 일련 번호를 기반으로 각 노드에 대해 고유한 20자리 일련 번호를 생성합니다.
* ONTAP Select 노드의 요청에 따라 공유 용량 풀의 용량에 대한 임대를 생성합니다.
* 배포 사용자 인터페이스를 통해 풀 사용 정보 보고




== 임대 특성

용량 풀 라이선스를 사용하는 노드에서 모든 데이터 집계에 할당된 스토리지에는 연관된 임대가 있어야 합니다. 노드가 스토리지 임대를 요청하면, 해당 용량을 사용할 수 있으면 라이선스 관리자가 임대로 응답합니다. 각 임대에는 다음과 같은 명시적 또는 암시적 속성이 있습니다.

* License Manager 모든 ONTAP Select 노드는 하나의 License Manager 인스턴스와 연결됩니다.
* 용량 풀 모든 ONTAP Select 노드는 하나의 용량 풀과 연결됩니다.
* 저장 할당 임대 계약에는 특정 용량 값이 할당됩니다.
* 만료일 및 시간 임대 기간은 사용자 구성에 따라 1시간에서 7일 사이입니다.




== 라이센스 잠금 ID

License Manager의 각 인스턴스와 그에 해당하는 Deploy 유틸리티 인스턴스는 고유한 128비트 숫자로 식별됩니다. 이 숫자는 9자리 용량 풀 라이선스 일련 번호와 결합되어 풀을 특정 License Manager 인스턴스(실제로는 Deploy 인스턴스)에 고정합니다. NetApp 라이선스 파일(NLF)을 생성할 때 NetApp 지원 사이트에서 두 값을 모두 제공해야 합니다.

다음과 같은 방법으로 웹 사용자 인터페이스를 사용하여 Deploy 인스턴스의 라이선스 잠금 ID를 확인할 수 있습니다.

* 시작하기 페이지: 이 페이지는 Deploy에 처음 로그인하면 표시됩니다. 페이지 오른쪽 상단의 드롭다운 상자를 클릭하고 "시작하기"를 선택하여 페이지를 표시할 수도 있습니다. LLID는 "라이선스 추가" 섹션에 표시됩니다.
* 관리 페이지 상단의 *관리* 탭을 클릭한 다음, *시스템* 및 *설정*을 클릭합니다.




== 기본 임대 운영

ONTAP Select 노드는 데이터 집계가 생성, 확장 또는 변경될 때마다 유효한 용량 임대를 찾거나 요청해야 합니다. 이전 요청에서 얻은, 아직 유효한 임대를 사용하거나, 필요한 경우 새 임대를 요청할 수 있습니다. ONTAP Select 노드는 용량 풀 임대를 찾기 위해 다음 단계를 수행합니다.

. 기존 임대가 노드에 있는 경우 다음 조건이 모두 충족되는 한 해당 임대가 사용됩니다.
+
** 임대 기간이 만료되지 않았습니다
** 집합체에 대한 저장 요청은 임대 용량을 초과하지 않습니다.


. 기존 임대를 찾을 수 없는 경우 노드는 라이선스 관리자에게 새 임대를 요청합니다.




== 저장 용량을 용량 풀로 반환

스토리지 용량은 필요에 따라 용량 풀에서 할당되며, 새로운 요청이 발생할 때마다 풀의 사용 가능한 스토리지 용량이 줄어들 수 있습니다. 스토리지 용량은 다음과 같은 여러 상황에서 풀로 반환됩니다.

* 데이터 집계에 대한 임대가 만료되었으며 노드에서 갱신되지 않습니다.
* 데이터 집계가 삭제되었습니다



NOTE: ONTAP Select 가상 머신이 삭제되면 활성 임대는 만료될 때까지 유효합니다. 만료되면 용량이 풀로 반환됩니다.
