---
sidebar: sidebar 
permalink: reference_plan_ots_storage.html 
keywords: plan, planning, storage, software raid, hardware raid, raid, nvme 
summary: 고려해야 할 ONTAP Select 호스트 스토리지와 관련된 몇 가지 계획 문제가 있습니다. 
---
= ONTAP Select 스토리지 및 RAID 고려 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
고려해야 할 ONTAP Select 호스트 스토리지와 관련된 몇 가지 계획 문제가 있습니다.


NOTE: 외부 저장소 지원 정보는 다음에 설명되어 있습니다.link:reference_plan_ots_vnas.html["ONTAP Select vNAS 요구 사항"] .



== 하드웨어 RAID 컨트롤러 요구 사항

ONTAP Select 배포하는 하이퍼바이저 호스트의 RAID 컨트롤러는 여러 가지 요구 사항을 충족해야 합니다.


NOTE: ONTAP Select 실행되는 호스트에는 하드웨어 RAID 컨트롤러 또는 ONTAP Select 에서 제공하는 소프트웨어 RAID 기능을 사용할 경우 로컬 물리적 드라이브가 필요합니다. ONTAP Select vNAS 솔루션을 사용하여 외부 스토리지에 액세스하는 경우 로컬 RAID 컨트롤러와 소프트웨어 RAID 기능은 사용되지 않습니다.

RAID 컨트롤러의 최소 요구 사항은 다음과 같습니다.

* 12Gbps 처리량
* 512MB 내부 배터리 백업 또는 플래시(SuperCAP) 캐시
* 쓰기 백 모드로 구성됨:
+
** "쓰기"로 장애 복구 모드를 활성화합니다(지원되는 경우)
** "항상 미리 읽기" 정책 활성화(지원되는 경우)


* RAID 컨트롤러 뒤에 있는 모든 로컬 디스크는 단일 RAID 그룹으로 구성해야 합니다. 필요한 경우 여러 RAID 컨트롤러를 사용할 수 있습니다.
+
** 데이터 무결성을 유지하는 데 중요한 RAID 그룹의 로컬 드라이브 캐시를 비활성화합니다.


* LUN 구성은 다음 지침에 따라 수행해야 합니다.
+
** RAID 그룹 크기가 최대 LUN 크기인 64TB를 초과하는 경우 RAID 그룹 내의 사용 가능한 모든 저장 공간을 소모하도록 여러 개의 동일한 크기의 LUN을 구성해야 합니다.
** RAID 그룹 크기가 최대 LUN 크기인 64TB보다 작으면 RAID 그룹 내의 모든 사용 가능한 저장 공간을 소비하는 하나의 LUN을 구성해야 합니다.






== 소프트웨어 RAID 요구 사항

하이퍼바이저에 ONTAP Select 클러스터를 배포할 때 로컬 하드웨어 RAID 컨트롤러 대신 ONTAP Select 에서 제공하는 소프트웨어 RAID 기능을 활용할 수 있습니다. 소프트웨어 RAID를 사용하여 클러스터를 배포하기 전에 알아야 할 몇 가지 요구 사항과 제한 사항이 있습니다.



=== 일반 요구 사항

소프트웨어 RAID 배포 환경은 다음과 같은 핵심 요구 사항을 충족해야 합니다.

* VMware ESXi 7.0 GA(빌드 15843807) 이상
* ONTAP Select 프리미엄 라이선스 이상
* 로컬 SSD 드라이브만
* 시스템 디스크를 루트 및 데이터 집계에서 분리
* 호스트에 하드웨어 RAID 컨트롤러가 없습니다.



NOTE: 하드웨어 RAID 컨트롤러가 있는 경우 다음을 참조하세요.link:concept_stor_concepts_chars.html["심층 저장"] 추가 구성 요구 사항에 대한 섹션입니다.



=== ESXi 특정 요구 사항

* VMware ESXi 7.0 GA(빌드 15843807) 이상
* VMware VMotion, HA 및 DRS는 지원되지 않습니다.
* ONTAP Select 9.4 이하 버전에서 업그레이드된 노드에서는 소프트웨어 RAID를 사용할 수 없습니다. 이 경우, 소프트웨어 RAID 구축을 위해 새 노드를 생성해야 합니다.




=== KVM 특정 요구 사항

특정 소프트웨어 패키지 구성 요구 사항도 있습니다. 를 참조하십시오link:https://docs.netapp.com/us-en/ontap-select/kvm-host-configuration-and-preparation-checklist.html#prepare-linux-server["리눅스 서버 준비"] 자세한 내용은 다음 단계를 참조하세요.

KVM에 대한 미디어 기대:: 사용되는 SSD 플래시 저장 장치는 다음과 같은 추가 요구 사항을 충족해야 합니다.
+
--
* SSD 장치는 다음 방법을 통해 Linux 호스트에 정확하고 지속적으로 보고해야 합니다.
+
** # cat /sys/block/<장치>/queue/rotational
+
이러한 명령에 대해 보고된 값은 '0'이어야 합니다.



* 장치가 HBA 또는 경우에 따라 JBOD 모드로 작동하도록 구성된 RAID 컨트롤러에 연결되어 있을 것으로 예상됩니다. RAID 컨트롤러를 사용하는 경우, 장치 기능은 RAID 기능을 오버레이하지 않고 호스트를 통과해야 합니다. JBOD 모드에서 RAID 컨트롤러를 사용하는 경우, RAID 설명서를 검토하거나 필요에 따라 공급업체에 문의하여 장치의 회전 속도가 '0'으로 표시되는지 확인하십시오.
* 두 개의 별도 저장 구성 요소가 있습니다.
+
** 가상 머신 스토리지
+
ONTAP Select 가상 머신을 호스팅하는 데 사용되는 시스템 데이터가 포함된 LVM 풀(스토리지 풀)입니다. LVM 풀은 내구성이 뛰어난 플래시 디바이스로 백업되어야 하며, SAS, SATA 또는 NVMe 중 선택 가능합니다. 성능 향상을 위해서는 NVMe 디바이스 사용을 권장합니다.

** 데이터 디스크
+
데이터 관리에 사용되는 SAS 또는 SATA SSD 드라이브 세트입니다. SSD 장치는 엔터프라이즈급이며 내구성이 뛰어나야 합니다. NVMe 인터페이스는 지원되지 않습니다.



* 모든 장치는 512BPS로 포맷되어야 합니다.


--




=== ONTAP Select 노드 구성

시스템 디스크를 루트 및 데이터 집계에서 분리하려면 다음과 같이 각 ONTAP Select 노드와 하이퍼바이저 호스트를 구성해야 합니다.

* 시스템 스토리지 풀 생성 ONTAP Select 시스템 데이터에 대한 스토리지 풀을 생성해야 합니다. ONTAP Select 노드를 구성하는 과정에서 스토리지 풀을 연결해야 합니다.
* 필요한 물리적 디스크 연결 하이퍼바이저 호스트에는 ONTAP Select 가상 머신에서 사용할 수 있도록 필요한 SSD 디스크가 연결되어 있어야 합니다. 이 드라이브에는 루트 및 데이터 집계가 저장됩니다. ONTAP Select 노드 구성 과정에서 스토리지 디스크를 연결해야 합니다.




== 저장 용량 제한

ONTAP Select 배포를 계획하는 과정에서 스토리지 할당 및 사용과 관련된 제한 사항을 알고 있어야 합니다.

가장 중요한 저장 제한 사항은 아래와 같습니다. 또한 다음을 검토해야 합니다.link:https://mysupport.netapp.com/matrix/["상호 운용성 매트릭스 도구"^] 더 자세한 정보를 원하시면.


TIP: ONTAP Select 스토리지 할당 및 사용과 관련된 몇 가지 제한 사항을 적용합니다. ONTAP Select 합니다. 를 참조하십시오link:https://docs.netapp.com/us-en/ontap-select/concept_lic_evaluation.html["특허"] 자세한 내용은 섹션을 참조하세요.



=== 원시 저장 용량 계산

ONTAP Select 스토리지 용량은 ONTAP Select 가상 머신에 연결된 가상 데이터와 루트 디스크의 총 허용 크기에 해당합니다. 용량을 할당할 때 이 점을 고려해야 합니다.



=== 단일 노드 클러스터의 최소 저장 용량

단일 노드 클러스터의 노드에 할당된 스토리지 풀의 최소 크기는 다음과 같습니다.

* 평가: 500GB
* 생산량: 1.0TB


프로덕션 배포에 대한 최소 할당은 사용자 데이터에 대한 1TB와 다양한 ONTAP Select 내부 프로세스에 사용되는 약 266GB로 구성되며, 이는 필요한 오버헤드로 간주됩니다.



=== 다중 노드 클러스터의 최소 저장 용량

다중 노드 클러스터의 각 노드에 할당된 스토리지 풀의 최소 크기는 다음과 같습니다.

* 평가: 1.9TB
* 생산량: 2.0TB


프로덕션 배포에 대한 최소 할당은 사용자 데이터에 대한 2TB와 다양한 ONTAP Select 내부 프로세스에 사용되는 약 266GB로 구성되며, 이는 필요한 오버헤드로 간주됩니다.

[NOTE]
====
HA 쌍의 각 노드는 동일한 저장 용량을 가져야 합니다.

HA 쌍의 스토리지 용량을 예측할 때는 모든 집계(루트 및 데이터)가 미러링된다는 점을 고려해야 합니다. 따라서 집계의 각 플렉스는 동일한 양의 스토리지를 사용합니다.

예를 들어, 2TB 집계가 생성되면 두 개의 플렉스 인스턴스(plex0에 2TB, plex1에 2TB)에 2TB를 할당하거나 총 라이선스된 저장 용량의 4TB를 할당합니다.

====


=== 저장 용량 및 다중 저장 풀

로컬 직접 연결 스토리지, VMware vSAN 또는 외부 스토리지 어레이를 사용할 경우 각 ONTAP Select 노드가 최대 400TB의 스토리지를 사용하도록 구성할 수 있습니다. 그러나 직접 연결 스토리지 또는 외부 스토리지 어레이를 사용할 경우 단일 스토리지 풀의 최대 크기는 64TB입니다. 따라서 이러한 상황에서 64TB 이상의 스토리지를 사용하려는 경우 다음과 같이 여러 스토리지 풀을 할당해야 합니다.

* 클러스터 생성 프로세스 중에 초기 스토리지 풀을 할당합니다.
* 하나 이상의 추가 스토리지 풀을 할당하여 노드 스토리지를 늘립니다.



NOTE: 각 스토리지 풀에서 2% 버퍼는 사용되지 않은 상태로 유지되며 용량 라이선스가 필요하지 않습니다. 이 스토리지는 용량 제한이 지정되지 않는 한 ONTAP Select 에서 사용되지 않습니다. 용량 제한이 지정된 경우, 지정된 용량이 2% 버퍼 영역에 속하지 않는 한 해당 용량의 스토리지가 사용됩니다. 이 버퍼는 스토리지 풀의 모든 공간을 할당하려고 할 때 발생하는 오류를 방지하기 위해 필요합니다.



=== 스토리지 용량 및 VMware vSAN

VMware vSAN을 사용할 경우 데이터스토어는 64TB보다 클 수 있습니다. 그러나 ONTAP Select 클러스터를 생성할 때는 처음에는 최대 64TB까지만 할당할 수 있습니다. 클러스터가 생성된 후에는 기존 vSAN 데이터스토어에서 추가 스토리지를 할당할 수 있습니다. ONTAP Select 에서 사용할 수 있는 vSAN 데이터스토어 용량은 VM 스토리지 정책 설정에 따라 결정됩니다.



=== 모범 사례

하이퍼바이저 코어 하드웨어와 관련하여 다음 권장 사항을 고려해야 합니다.

* 단일 ONTAP Select 집합에 있는 모든 드라이브는 동일한 유형이어야 합니다. 예를 들어, 동일한 집합에 HDD와 SSD 드라이브를 함께 사용해서는 안 됩니다.




== 플랫폼 라이선스에 따른 추가 디스크 드라이브 요구 사항

선택하는 드라이브는 플랫폼 라이선스 제공에 따라 제한됩니다.


NOTE: 디스크 드라이브 요구 사항은 로컬 RAID 컨트롤러 및 드라이브뿐 아니라 소프트웨어 RAID를 사용할 때도 적용됩니다. 이러한 요구 사항은 ONTAP Select vNAS 솔루션을 통해 액세스하는 외부 스토리지에는 적용되지 않습니다.

.기준
* 8~60개의 내장 HDD(NL-SAS, SATA, 10K SAS)


.프리미엄
* 8~60개의 내장 HDD(NL-SAS, SATA, 10K SAS)
* 4~60개의 내장 SSD


.프리미엄 XL
* 8~60개의 내장 HDD(NL-SAS, SATA, 10K SAS)
* 4~60개의 내장 SSD
* 4~14개의 내부 NVMe



NOTE: 로컬 DAS 드라이브가 있는 소프트웨어 RAID는 프리미엄 라이선스(SSD만 해당) 및 프리미엄 XL 라이선스(SSD 또는 NVMe)에서 지원됩니다.



== 소프트웨어 RAID가 있는 NVMe 드라이브

NVMe SSD 드라이브를 사용하도록 소프트웨어 RAID를 구성할 수 있습니다. 사용자 환경은 다음 요구 사항을 충족해야 합니다.

* 지원되는 Deploy 관리 유틸리티를 사용한 ONTAP Select
* 프리미엄 XL 플랫폼 라이선스 제공 또는 90일 평가 라이선스
* VMware ESXi 버전 6.7 이상
* 사양 1.0 이상을 준수하는 NVMe 장치


NVMe 드라이브를 사용하기 전에 수동으로 구성해야 합니다. 보다link:task_chk_nvme_configure.html["NVMe 드라이브를 사용하도록 호스트 구성"] 자세한 내용은.
