---
sidebar: sidebar 
permalink: reference_plan_best_practices.html 
keywords: plan, planning, best practices, recommendations 
summary: ONTAP Select 배포를 계획할 때 고려해야 할 모범 사례가 있습니다. 
---
= ONTAP Select 배포를 위한 모범 사례 요약
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 배포를 계획할 때 고려해야 할 모범 사례가 있습니다.



== 스토리지

저장을 위해 다음의 모범 사례를 고려해 보세요.



=== 올플래시 또는 일반 플래시 어레이

올플래시 VSAN 또는 일반 플래시 어레이를 사용하는 ONTAP Select 가상 NAS(vNAS) 배포는 SSD가 아닌 DAS 스토리지를 사용하는 ONTAP Select 대한 모범 사례를 따라야 합니다.



=== 외부 저장소

다음 권장 사항을 준수해야 합니다.

* ONTAP Select 네트워크 및 외부 스토리지에 대한 전용 네트워크 포트, 대역폭 및 vSwitch 구성을 정의합니다.
* 저장소 활용을 제한하기 위한 용량 옵션 구성(ONTAP Select 외부 저장소 풀의 전체 용량을 사용할 수 없음)
* 가능한 경우 모든 외부 스토리지 어레이가 사용 가능한 중복성 및 HA 기능을 사용하는지 확인하십시오.




=== 하이퍼바이저 코어 하드웨어

단일 ONTAP Select 집합에 있는 모든 드라이브는 동일한 유형이어야 합니다. 예를 들어, 동일한 집합에 HDD와 SSD 드라이브를 함께 사용해서는 안 됩니다.



=== RAID 컨트롤러

서버 RAID 컨트롤러는 쓰기 저장 모드로 작동하도록 구성해야 합니다. 쓰기 작업 부하 성능 문제가 발생하면 컨트롤러 설정을 확인하고 쓰기 저장(Writethrough) 또는 쓰기 저장(Writearound) 기능이 활성화되어 있지 않은지 확인하십시오.

물리적 서버에 로컬로 연결된 모든 디스크를 관리하는 단일 RAID 컨트롤러가 있는 경우, NetApp 서버 OS용으로 별도의 LUN과 ONTAP Select 용으로 하나 이상의 LUN을 생성할 것을 권장합니다. 부팅 디스크가 손상되는 경우, 이 모범 사례를 통해 관리자는 ONTAP Select 영향을 주지 않고 OS LUN을 다시 생성할 수 있습니다.

RAID 컨트롤러 캐시는 NVRAM 파티션에 대한 변경 사항뿐만 아니라 모든 수신 블록 변경 사항을 저장하는 데 사용됩니다. 따라서 RAID 컨트롤러를 선택할 때는 사용 가능한 가장 큰 캐시 용량을 가진 컨트롤러를 선택하십시오. 캐시 용량이 클수록 디스크 플러싱 빈도가 줄어들고 ONTAP Select VM, 하이퍼바이저 및 서버에 함께 배치된 모든 컴퓨팅 VM의 성능이 향상됩니다.



=== RAID 그룹

최적의 RAID 그룹 크기는 8~12개입니다. RAID 그룹당 최대 드라이브 수는 24개입니다.

ONTAP Select 노드당 지원되는 NVME 드라이브의 최대 수는 14개입니다.

스페어 디스크는 선택 사항이지만 권장됩니다. NetApp RAID 그룹당 스페어 디스크를 하나씩 사용할 것을 권장하지만, 모든 RAID 그룹에 글로벌 스페어 디스크를 사용할 수도 있습니다. 예를 들어, 각 RAID 그룹을 8~12개의 드라이브로 구성하고 RAID 그룹 3개마다 스페어 디스크 2개를 사용할 수 있습니다.

ONTAP Select RAID 그룹 내 LUN 수를 늘려도 성능 향상 효과가 없습니다. 여러 LUN은 SATA/NL-SAS 구성 모범 사례를 따르거나 하이퍼바이저 파일 시스템 제한을 우회하는 경우에만 사용해야 합니다.



=== VMware ESXi 호스트

NetApp 시스템 디스크를 호스팅하는 데이터 저장소에 ESX 6.5 U2 이상과 NVMe 디스크를 사용할 것을 권장합니다. 이 구성은 NVRAM 파티션에 최상의 성능을 제공합니다.


NOTE: ESX 6.5 U2 이상에 설치할 경우 ONTAP Select 시스템 디스크가 SSD에 있든 NVMe 디스크에 있든 관계없이 vNVMEe 드라이버를 사용합니다. 이렇게 하면 VM 하드웨어 수준이 ESX 6.5 이상과 호환되는 13으로 설정됩니다.

ONTAP Select 네트워크 및 외부 스토리지(iSCSI 또는 NFS를 사용할 때 VMware vSAN 및 일반 스토리지 어레이 트래픽)에 대한 전용 네트워크 포트, 대역폭 및 vSwitch 구성을 정의합니다.

저장소 활용을 제한하기 위해 용량 옵션을 구성합니다(ONTAP Select 외부 vNAS 데이터 저장소의 전체 용량을 사용할 수 없습니다).

가능한 경우 모든 일반 외부 스토리지 어레이가 사용 가능한 중복성 및 HA 기능을 사용하도록 합니다.



=== VMware 스토리지 vMotion

ONTAP Select 노드와 함께 VMware Storage vMotion을 사용할지 여부를 결정할 때 새 호스트의 사용 가능한 용량이 유일한 요소는 아닙니다. 기본 스토리지 유형, 호스트 구성 및 네트워크 성능은 기존 호스트와 동일한 워크로드를 감당할 수 있어야 합니다.



== 네트워킹

네트워킹을 위해 다음의 모범 사례를 고려해 보세요.



=== 중복된 MAC 주소

여러 Deploy 인스턴스가 중복된 MAC 주소를 할당할 가능성을 없애려면 2계층 네트워크당 하나의 Deploy 인스턴스를 사용하여 ONTAP Select 클러스터 또는 노드를 만들거나 관리해야 합니다.



=== EMS 메시지

ONTAP Select 2노드 클러스터에서 스토리지 장애 조치가 비활성화되었음을 나타내는 EMS 메시지가 나타나는지 주의 깊게 모니터링해야 합니다. 이러한 메시지는 중재자 서비스 연결이 끊어졌음을 나타내므로 즉시 수정해야 합니다.



=== 노드 간 지연 시간

두 노드 간의 네트워크는 평균 5ms의 지연 시간과 5ms의 주기적 지터를 지원해야 합니다. 클러스터를 구축하기 전에 ONTAP Select 제품 아키텍처 및 모범 사례 기술 보고서에 설명된 절차에 따라 네트워크를 테스트하십시오.



=== 부하 분산

내부 및 외부 ONTAP Select 네트워크에서 부하 분산을 최적화하려면 원래 가상 포트 기반 경로 부하 분산 정책을 사용합니다.



=== 다중 레이어 2 네트워크

데이터 트래픽이 여러 개의 2계층 네트워크에 걸쳐 있고 VLAN 포트를 사용해야 하거나 여러 IP 공간을 사용하는 경우 VGT를 사용해야 합니다.



=== 물리적 스위치 구성

VMware는 ESXi 호스트에 연결된 스위치 포트에서 STP를 Portfast로 설정할 것을 권장합니다. 스위치 포트에서 STP를 Portfast로 설정하지 않으면 ONTAP Select 업링크 장애 허용 기능에 영향을 줄 수 있습니다. LACP를 사용하는 경우 LACP 타이머를 고속(1초)으로 설정해야 합니다. 부하 분산 정책은 포트 그룹에서 IP 해시 기반 경로로, LAG에서는 소스 및 대상 IP 주소, TCP/UDP 포트 및 VLAN으로 설정해야 합니다.



=== KVM용 가상 스위치 옵션

외부 네트워크와 내부 네트워크(다중 노드 클러스터만 해당)를 지원하려면 각 ONTAP Select 호스트에 가상 스위치를 구성해야 합니다. 다중 노드 클러스터를 배포하는 과정에서 내부 클러스터 네트워크의 네트워크 연결을 테스트해야 합니다.

하이퍼바이저 호스트에서 Open vSwitch를 구성하는 방법에 대해 자세히 알아보려면 다음을 참조하세요.link:https://www.netapp.com/media/13134-tr4613.pdf["KVM 제품 아키텍처 및 모범 사례에 대한 ONTAP Select"^] 기술 보고서.



== 하아

고가용성을 위해 다음과 같은 모범 사례를 고려해야 합니다.



=== 백업 배포

클러스터를 생성한 후에도 배포 구성 데이터를 정기적으로 백업하는 것이 가장 좋습니다. 특히 2노드 클러스터의 경우, 중재자 구성 데이터가 백업에 포함되므로 더욱 중요합니다.

클러스터를 생성하거나 배포한 후에는 다음을 수행해야 합니다.link:task_cli_clusters.html["ONTAP Select Deploy 구성 데이터 백업"] .



=== 미러링된 집계

기본 집계의 최신(RPO 0) 복사본을 제공하기 위해서는 미러링된 집계가 필요하지만, 기본 집계의 여유 공간이 부족하지 않도록 주의해야 합니다. 기본 집계 의 여유 공간이 부족하면 ONTAP 스토리지 반환 기준으로 사용되는 공통 스냅샷 복사본을 삭제할 수 있습니다. 이는 클라이언트 쓰기 작업을 수용하기 위해 설계된 방식입니다. 그러나 장애 복구 시 공통 스냅샷 복사본이 없기 때문에 ONTAP Select 노드는 미러링된 집계에서 전체 기준선을 생성해야 합니다. 이 작업은 공유되지 않는 환경에서는 상당한 시간이 소요될 수 있습니다.


NOTE: NetApp 최적의 스토리지 성능 및 가용성을 위해 미러링된 집계에 최소 20%의 여유 공간을 유지할 것을 권장합니다. 미러링되지 않은 집계의 경우 권장 용량은 10%이지만, 파일 시스템은 추가된 10%의 공간을 증분 변경 사항을 처리하는 데 사용할 수 있습니다. ONTAP의 COW(기록 중 복사) 스냅샷 기반 아키텍처로 인해 증분 변경은 미러링된 집계의 공간 사용량을 증가시킵니다. 이러한 모범 사례를 준수하지 않으면 성능에 부정적인 영향을 미칠 수 있습니다. 고가용성 인수는 데이터 집계가 미러링된 집계로 구성된 경우에만 지원됩니다.



=== NIC 집계, 팀 구성 및 장애 조치

ONTAP Select 2노드 클러스터에 대해 단일 10Gb 링크를 지원합니다. 그러나 ONTAP Select 클러스터의 내부 및 외부 네트워크 모두에서 NIC 집계 또는 NIC 팀을 통해 하드웨어 중복성을 확보하는 것이 NetApp 모범 사례입니다.

NIC에 여러 개의 ASIC(Application Specific Integrated Circuit)이 있는 경우, 내부 및 외부 네트워크에 대한 NIC 팀을 통해 네트워크 구조를 구축할 때 각 ASIC에서 하나의 네트워크 포트를 선택합니다.

NetApp ESX와 물리적 스위치 모두에서 LACP 모드를 활성화할 것을 권장합니다. 또한 물리적 스위치, 포트, 포트 채널 인터페이스 및 VMNIC에서 LACP 타이머를 빠름(1초)으로 설정해야 합니다.

LACP가 있는 분산 vSwitch를 사용하는 경우 NetApp LAG의 포트 그룹, 소스 및 대상 IP 주소, TCP/UDP 포트, VLAN에서 IP 해시 기반 라우팅으로 부하 분산 정책을 구성할 것을 권장합니다.



=== 2노드 확장 HA(MetroCluster SDS) 모범 사례

MetroCluster SDS를 만들기 전에 ONTAP Deploy 연결 검사기를 사용하여 두 데이터 센터 간의 네트워크 지연 시간이 허용 범위 내에 있는지 확인하세요.

가상 게스트 태깅(VGT) 및 2노드 클러스터를 사용할 때는 추가 주의 사항이 있습니다. 2노드 클러스터 구성에서는 ONTAP 완전히 사용 가능해지기 전에 노드 관리 IP 주소를 사용하여 중재자와의 조기 연결을 설정합니다. 따라서 노드 관리 LIF(포트 e0a)에 매핑된 포트 그룹에서는 외부 스위치 태깅(EST) 및 가상 스위치 태깅(VST)만 지원됩니다. 또한, 관리 트래픽과 데이터 트래픽이 모두 동일한 포트 그룹을 사용하는 경우, 전체 2노드 클러스터에 대해 EST와 VST만 지원됩니다.
