---
sidebar: sidebar 
permalink: reference_plan_ots_mcc_sds.html 
keywords: plan, planning, metrocluster, metrocluster sds 
summary: ONTAP Select 배포를 계획할 때 고려해야 할 MetroCluster SDS에 대한 몇 가지 요구 사항이 있습니다. 
---
= ONTAP Select MetroCluster SDS 배포 준비
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
MetroCluster SDS는 2노드 ONTAP Select 클러스터를 생성할 때 사용할 수 있는 구성 옵션입니다. 원격 사무실/지사(ROBO) 배포와 유사하지만, 두 노드 간 거리는 최대 10km까지 가능합니다. 이 향상된 2노드 배포는 추가적인 사용 사례를 제공합니다. MetroCluster SDS 배포를 준비할 때는 요구 사항과 제한 사항을 숙지해야 합니다.

MetroCluster SDS를 배포하기 전에 다음 요구 사항이 충족되는지 확인하세요.

.라이센스
각 노드에는 프리미엄 이상의 ONTAP Select 라이선스가 있어야 합니다.

.하이퍼바이저 플랫폼
MetroCluster SDS는 ROBO 환경의 2노드 클러스터에 지원되는 것과 동일한 VMware ESXi 및 KVM 하이퍼바이저에 배포될 수 있습니다.

[NOTE]
====
ONTAP Select 9.14.1부터 KVM 하이퍼바이저 지원이 다시 시작되었습니다. 이전에는 ONTAP Select 9.10.1에서 KVM 하이퍼바이저에 새 클러스터를 배포하는 기능이 제거되었고, ONTAP Select Select 9.11.1에서는 오프라인으로 전환하거나 삭제하는 기능을 제외한 기존 KVM 클러스터 및 호스트 관리 기능이 제거되었습니다.

====
.네트워크 구성
참여 사이트 간에는 레이어 2 연결이 필요합니다. 다음 구성을 포함하여 10GbE와 1GbE가 모두 지원됩니다.

* 1 x 10GbE
* 4 x 1GbE



NOTE: 데이터 제공 포트와 상호 연결 포트는 동일한 첫 번째 스위치에 연결되어야 합니다.

.노드 간 지연 시간
두 노드 간의 네트워크는 평균 5ms의 지연 시간과 5ms의 주기적 지터를 지원해야 합니다. 클러스터를 배포하기 전에 다음 절차에 따라 네트워크를 테스트해야 합니다.link:concept_nw_concepts_chars.html["심층 네트워킹"] 부분.

.중재 서비스
모든 2노드 ONTAP Select 클러스터와 마찬가지로, Deploy 가상 머신에는 노드를 모니터링하고 장애 관리를 지원하는 별도의 중재자 서비스가 포함되어 있습니다. MetroCluster SDS의 향상된 거리를 통해 네트워크 토폴로지에 세 개의 개별 사이트가 생성됩니다. 중재자와 노드 간 링크 지연 시간은 왕복 125ms 이하여야 합니다.

.스토리지
HDD와 SSD 디스크를 사용하는 직접 연결 스토리지(DAS)가 지원됩니다. VMware 환경의 외부 스토리지 어레이와 vSAN을 포함한 vNAS도 지원됩니다.


NOTE: MetroCluster SDS를 배포하는 경우 분산형 또는 "확장형" 토폴로지에서 vSAN을 사용할 수 없습니다.

.Deploy에 할당된 정적 IP 주소
Deploy 관리 유틸리티에 고정 IP 주소를 할당해야 합니다. 이 요구 사항은 하나 이상의 ONTAP Select 2노드 클러스터를 관리하는 모든 Deploy 인스턴스에 적용됩니다.
