---
sidebar: sidebar 
permalink: reference_faq.html 
keywords: faq, frequently asked questions 
summary: ONTAP Select 에 대한 일반적인 질문에 대한 답변을 찾아보세요. 
---
= ONTAP Select 에 대한 FAQ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 에 대한 자주 묻는 질문에 대한 답변을 찾을 수 있습니다.

[NOTE]
====
ONTAP Select 9.14.1부터 KVM 하이퍼바이저 지원이 다시 시작되었습니다. 이전에는 ONTAP Select 9.10.1에서 KVM 하이퍼바이저에 새 클러스터를 배포하는 기능이 제거되었고, ONTAP Select Select 9.11.1에서는 오프라인으로 전환하거나 삭제하는 기능을 제외한 기존 KVM 클러스터 및 호스트 관리 기능이 제거되었습니다.

====


== 일반적인

몇 가지 일반적인 질문과 답변이 있습니다.

.ONTAP Select Deploy와 ONTAP Select 의 차이점은 무엇입니까?
ONTAP Select Deploy는 ONTAP Select 클러스터를 생성하는 데 사용되는 유틸리티입니다. 현재 ONTAP Select Deploy는 프로덕션 클러스터를 생성하는 데 사용할 수 있는 유일한 방법입니다. ONTAP Select Deploy는 클라이언트가 프로덕션 배포의 실제 단계를 테스트하고 문서화할 수 있도록 평가판 Select 클러스터를 생성하는 데에도 사용할 수 있습니다. 또한 ONTAP Select Deploy는 평가 기간 동안 사용된 공간을 충당할 수 있는 충분한 용량을 갖춘 적절한 용량 계층 라이선스를 사용하여 평가판 클러스터를 프로덕션 클러스터로 변환할 수도 있습니다.

ONTAP Select Deploy는 ONTAP Select 이미지가 포함된 가상 머신입니다. 클러스터 설치 중에 ONTAP Select Deploy는 ONTAP Select 최소 요구 사항이 충족되는지 확인하기 위해 여러 가지 검사를 수행합니다. ONTAP Select Deploy VM과 Select 클러스터는 별도로 업그레이드할 수 있습니다.

.ONTAP Select 의 성능 문제를 어떻게 해결할 수 있나요?
FAS 의 ONTAP 과 마찬가지로, 성능 데이터는 perfstat 유틸리티를 사용하여 수집해야 합니다. 다음은 샘플 명령입니다.

[listing]
----
perfstat8 –i N,m -t <sample time in minutes> --verbose --nodes=<filer IP> --diag-passwd=abcxyz --mode="cluster-mode" > <name of output file>
----
.ONTAP Select Deploy의 Swagger API 페이지에 어떻게 액세스합니까?
[listing]
----
http://<Deploy-IP-Address/api/ui
----

NOTE: API v3 릴리스는 이전 버전의 API와 호환되지 않습니다. 새로운 API 절차가 다음에서 사용 가능합니다. https://library.netapp.com/ecm/ecm_download_file/ECMLP2845694["필드 포털"^] .

.ONTAP Select VM을 VMware나 다른 타사 스냅샷으로 백업할 수 있나요?
아니요. ONTAP Select VM은 VMware 기반 스냅샷에서 제외되는 독립형 영구 드라이브를 사용합니다. ONTAP Select 백업에는 SnapMirror 또는 SnapVault 만 지원됩니다.

.이 FAQ에 포함되지 않은 질문에 대한 설명은 어디에서 얻을 수 있나요?
연락하다link:mailto:ng-ses-ontap-select@netapp.com["ng-ses-ontap-select@netapp.com"] .



== 라이센스, 설치, 업그레이드 및 되돌리기

라이센스, 설치, 업그레이드 및 되돌리기와 관련된 여러 가지 질문과 답변이 있습니다.

.ONTAP Select 와 ONTAP Select Deploy를 개별적으로 업그레이드할 수 있나요?
네. ONTAP Select Deploy 유틸리티는 ONTAP Select 클러스터와 별도로 업그레이드할 수 있습니다. 마찬가지로, Select 클러스터도 ONTAP Select Deploy 유틸리티와 별도로 업그레이드할 수 있습니다.

.ONTAP Select FAS 클러스터와 동일한 절차로 업그레이드할 수 있나요?
네, Select 클러스터의 업그레이드 절차는 FAS 클러스터의 업그레이드와 동일합니다. 다만 ONTAP Select 업그레이드 바이너리는 FAS 업그레이드 바이너리의 ONTAP 과 별도로 다운로드해야 합니다.

.FAS 클러스터와 동일한 절차를 사용하여 ONTAP Select 되돌릴 수 있습니까?
네, ONTAP Select 클러스터의 되돌리기 절차는 FAS 클러스터의 되돌리기 절차와 거의 동일합니다. 하지만 몇 가지 차이점이 있습니다.

* 업그레이드된 ONTAP Select 인스턴스만 되돌릴 수 있으며, 원래 설치 버전까지만 가능합니다. ONTAP Select 일반적으로 이전 릴리스를 지원하더라도, 새로 설치한 버전은 이전 코드 릴리스로 되돌릴 수 없습니다.
* 소프트웨어 RAID를 사용하는 ONTAP Select (KVM) 및 ONTAP Select (ESX)의 경우, 소프트웨어 RAID를 지원하지 않는 이전 버전으로 되돌릴 수 없습니다. 또한, ESX에 ONTAP Select 9.5 이상을 새로 설치하면 VMXNET3 네트워크 드라이버와 가능한 경우 vNMVE 드라이버가 사용됩니다. 이러한 새 설치는 이전 버전의 ONTAP Select 로 되돌릴 수 없습니다.
* ONTAP Select VM도 대형 인스턴스(Premium XL 라이선스 사용)로 업그레이드된 경우, 9.6 이전 버전으로 되돌리는 것은 지원되지 않습니다. 대형 인스턴스 기능이 이전 버전에서는 제공되지 않기 때문입니다.


.ONTAP MetroCluster SDS에는 최소한 프리미엄 라이선스가 필요합니까?
네.

.ONTAP Select 클러스터 네트워크 구성을 설치 후에 변경할 수 있나요?
다음 ONTAP Select 클러스터 속성의 변경 사항은 UI, CLI 또는 REST API를 통해 사용 가능한 클러스터 새로 고침 작업을 사용하여 ONTAP Select Deploy에서 인식됩니다.

* 네트워크 구성(IP 주소, DNS, NTP, 넷마스크 및 게이트웨이)
* ONTAP Select


다음 ONTAP Select VM 변경 사항도 인식됩니다.

* ONTAP Select (예: 온라인 또는 오프라인)
* 호스트 네트워크 이름 및 스토리지 풀 이름 변경


ONTAP Select Deploy 2.6으로 업그레이드하면 이미 배포되었지만 원래 구성에서 변경되지 않은 모든 ONTAP Select 클러스터에 대해 이러한 변경 사항을 지원할 수 있습니다. 즉, 위에서 언급한 ONTAP Select 클러스터 속성이 System Manager 또는 vCenter를 사용하여 변경된 경우, ONTAP Select Deploy 2.6으로 업그레이드해도 이러한 불일치는 해결되지 않습니다. ONTAP ONTAP Select Deploy가 각 ONTAP Select VM에 고유한 메타데이터를 추가하려면 먼저 ONTAP ONTAP Select 속성 변경 사항을 롤백해야 합니다.

.ONTAP Select Deploy 네트워크 구성을 설치 후에 변경할 수 있나요?
Deploy 인스턴스가 특정 환경에서 실행된 후에는 해당 인스턴스의 네트워킹 세부 정보를 수정할 수 없습니다. 자세한 내용은 지식 기반 문서를 참조하세요.link:https://kb.netapp.com/onprem/ontap/ONTAP_Select/Modifying_DNS_configuration_of_ONTAP_Deploy_instance["ONTAP Deploy 인스턴스의 DNS 구성 수정"^] .

.Deploy는 ONTAP Select 라이선스가 갱신된 것을 어떻게 감지합니까?
모든 라이선스의 방법은 동일하지만, 구체적인 내용은 용량 계층 라이선스인지 용량 풀 라이선스인지에 따라 다릅니다.

* ONTAP Select Deploy는 NetApp 에서 업데이트된 라이선스 파일을 구매하면 라이선스 및 지원 계약이 갱신되는지 감지합니다. 라이센스 파일(.NLF)에는 용량, 시작 및 종료 날짜가 포함되어 있으며 다음에서 생성됩니다.link:https://mysupport.netapp.com/site/["NetApp 지원 사이트"^] 그런 다음 배포 서버에서 업데이트됩니다.
+

NOTE: *Add* 및 *Update* 함수를 사용하여 배포 서버에 NLF를 로드할 수 있습니다. *Add*는 서버에 새 라이선스를 추가하고, *Update*는 용량, 노드 라이선스(표준, 프리미엄, 프리미엄 XL), 지원 시작 및 종료일(용량 계층 라이선스), 구독 시작 및 종료일(용량 풀 라이선스) 등의 정보를 기존 파일에 업데이트합니다.

+

CAUTION: 라이선스 파일을 수정하지 마십시오. 수정하면 보안 키가 무효화되고 라이선스도 무효화됩니다.

* *용량 계층 라이선스*는 ONTAP Select 노드 일련 번호에 연결된 노드당 영구 라이선스입니다. 별도의 지원 계약과 함께 판매됩니다. 라이선스는 영구적이지만, ONTAP Select 업그레이드에 액세스하고 NetApp 기술 지원을 받으려면 지원 계약을 갱신해야 합니다. 용량이나 노드 크기와 같은 라이선스 매개변수를 변경하려면 유효한 지원 계약이 필요합니다.
+
용량 계층 라이선스 업데이트, 매개변수 변경 또는 지원 계약 갱신을 구매하려면 주문 시 노드 일련 번호가 필요합니다. 용량 계층 노드 일련 번호는 9자리 숫자이며 '32'로 시작합니다.

+
구매가 완료되고 라이선스 파일이 생성되면 *Update* 기능을 사용하여 배포 서버에 업로드됩니다.

* *용량 풀 라이선스*는 하나 이상의 클러스터를 배포하기 위해 특정 용량 및 노드 크기(표준, 프리미엄, 프리미엄 XL)의 풀을 사용할 수 있는 권한을 구독하는 것입니다. 이 구독에는 지정된 기간 동안 라이선스 사용 권한과 지원이 포함됩니다. 라이선스 사용 권한과 지원 계약에는 시작일과 종료일이 명시되어 있습니다.


.Deploy는 노드에 갱신된 라이센스나 지원 계약이 있는지 어떻게 감지합니까?
업데이트된 라이선스 파일을 구매, 생성 및 업로드하는 방식을 통해 Deploy는 갱신된 라이선스와 지원 계약을 감지합니다.

용량 계층 지원 계약 종료일이 지난 경우 노드는 계속 실행할 수 있지만 ONTAP 업데이트를 다운로드하고 설치할 수 없으며, 지원 계약을 최신 상태로 유지하지 않고는 NetApp 기술 지원에 도움을 요청할 수 없습니다.

용량 풀 구독이 만료되면 시스템에서 먼저 경고를 표시하지만 30일 후에 시스템이 종료되면 업데이트된 구독이 배포 서버에 설치될 때까지 재부팅되지 않습니다.



== 스토리지

저장과 관련된 질문과 답변이 여러 개 있습니다.

.단일 ONTAP Select Deploy 인스턴스가 ESX와 KVM 모두에 클러스터를 생성할 수 있나요?
네. ONTAP Select Deploy는 KVM 또는 ESX에 설치할 수 있으며, 두 설치 모두 두 하이퍼바이저 중 하나에 ONTAP Select 클러스터를 생성할 수 있습니다.

.ESX의 ONTAP Select 에 vCenter가 필요합니까?
ESX 호스트에 적절한 라이선스가 부여된 경우 vCenter Server에서 ESX 호스트를 관리할 필요가 없습니다. 그러나 vCenter Server에서 호스트를 관리하는 경우, 해당 vCenter Server를 사용하도록 ONTAP Select Deploy를 구성해야 합니다. 즉, vCenter Server에서 ESX 호스트를 적극적으로 관리하고 있는 경우 ONTAP Select Deploy에서 독립 실행형으로 구성할 수 없습니다. ONTAP Select Deploy VM은 vMotion 또는 VMware HA 이벤트로 인해 발생하는 ESXi 호스트 간의 모든 ONTAP Select VM 마이그레이션을 vCenter를 통해 추적합니다.

.소프트웨어 RAID란 무엇인가요?
ONTAP Select 하드웨어 RAID 컨트롤러가 없는 서버를 사용할 수 있습니다. 이 경우 RAID 기능은 소프트웨어로 구현됩니다. 소프트웨어 RAID를 사용하는 경우 SSD와 NVMe 드라이브가 모두 지원됩니다. ONTAP Select 부팅 디스크와 코어 디스크는 여전히 가상화된 파티션(스토리지 풀 또는 데이터스토어) 내에 있어야 합니다. ONTAP Select RD2(루트-데이터-데이터 파티셔닝)를 사용하여 SSD를 파티셔닝합니다. 따라서 ONTAP Select 루트 파티션은 데이터 집계에 사용되는 것과 동일한 물리적 스핀들에 상주합니다. 그러나 루트 집계와 부팅 디스크, 코어 가상화 디스크는 용량 라이선스에 포함되지 않습니다.

AFF/ FAS 에서 사용 가능한 모든 RAID 방식은 ONTAP Select 에서도 사용할 수 있습니다. 여기에는 RAID 4, RAID DP, RAID-TEC 포함됩니다. 최소 SSD 수는 선택한 RAID 구성 유형에 따라 다릅니다. 모범 사례에서는 최소 하나 이상의 예비 디스크가 필요합니다. 예비 디스크와 패리티 디스크는 용량 라이선스에 포함되지 않습니다.

.소프트웨어 RAID는 하드웨어 RAID 구성과 어떻게 다릅니까?
소프트웨어 RAID는 ONTAP 소프트웨어 스택의 한 계층입니다. 소프트웨어 RAID는 물리적 드라이브가 분할되어 ONTAP Select VM 내에서 원시 디스크로 사용 가능하므로 관리 제어 기능이 강화됩니다. 반면, 하드웨어 RAID는 일반적으로 하나의 대용량 LUN을 사용할 수 있으며, 이를 분할하여 ONTAP Select 내에서 볼 수 있는 VMDISK를 생성할 수 있습니다. 소프트웨어 RAID는 옵션으로 제공되며 하드웨어 RAID 대신 사용할 수 있습니다.

소프트웨어 RAID에 대한 몇 가지 요구 사항은 다음과 같습니다.

* ESX 및 KVM 지원
+
** ONTAP Select 9.14.1부터 KVM 하이퍼바이저 지원이 다시 시작되었습니다. 이전에는 ONTAP Select 9.10.1에서 KVM 하이퍼바이저 지원이 중단되었습니다.


* 지원되는 물리적 디스크 크기: 200GB – 32TB
* DAS 구성에서만 지원됩니다.
* SSD 또는 NVMe 지원
* Premium 또는 Premium XL ONTAP Select 라이선스가 필요합니다.
* 하드웨어 RAID 컨트롤러가 없거나 비활성화되어 있어야 하거나 SAS HBA 모드에서 작동해야 합니다.
* 시스템 디스크(코어 덤프, 부팅/ NVRAM 및 Mediator)에는 전용 LUN을 기반으로 하는 LVM 스토리지 풀 또는 데이터 저장소를 사용해야 합니다.


.KVM용 ONTAP Select 여러 개의 NIC 본드를 지원합니까?
KVM에 설치할 때는 단일 본드와 단일 브리지를 사용해야 합니다. 물리적 포트가 두 개 또는 네 개인 호스트는 모든 포트를 동일한 본드에 연결해야 합니다.

.ONTAP Select 하이퍼바이저 호스트의 물리적 디스크 또는 NIC 장애 발생 시 어떻게 보고하거나 알림을 제공합니까? ONTAP Select 이 정보를 하이퍼바이저에서 가져오는 건가요, 아니면 하이퍼바이저 수준에서 모니터링을 설정해야 하나요?
하드웨어 RAID 컨트롤러를 사용하는 경우, ONTAP Select 근본적인 서버 문제를 거의 인식하지 못합니다. 서버가 모범 사례에 따라 구성된 경우 일정 수준의 중복성이 유지되어야 합니다. 드라이브 장애 발생 시 복구를 위해 RAID 5/6을 권장합니다. 소프트웨어 RAID 구성의 경우, ONTAP 은 디스크 장애 발생 시 알림을 보내고, 예비 드라이브가 있는 경우 드라이브 재구축을 시작합니다.

네트워크 계층에서 단일 장애 지점을 방지하려면 최소 두 개의 물리적 NIC를 사용해야 합니다. NetApp 데이터, 관리 및 내부 포트 그룹의 NIC 팀 구성 및 본딩을 팀 또는 본딩에 두 개 이상의 업링크로 구성할 것을 권장합니다. 이러한 구성은 업링크 장애 발생 시 가상 스위치가 장애가 발생한 업링크의 트래픽을 NIC 팀의 정상 업링크로 이동하도록 보장합니다. 권장되는 네트워크 구성에 대한 자세한 내용은 다음을 참조하세요.link:reference_plan_best_practices.html#networking["모범 사례 요약: 네트워킹"] .

2노드 또는 4노드 클러스터의 경우 다른 모든 오류는 ONTAP HA에서 처리합니다. 하이퍼바이저 서버를 교체해야 하고 ONTAP Select 클러스터를 새 서버로 재구성해야 하는 경우 ONTAP Select 노드를 복구할 수 있나요?_를 참조하세요.

.ONTAP Select 노드를 복구할 수 있나요?
예를 들어 ONTAP Select VM이나 호스트가 완전히 손실되거나 단일 노드 클러스터가 실수로 삭제된 경우 ONTAP Select 노드를 복구해야 하는 경우 NetApp 기술 지원팀에 문의하세요. 자세한 내용은 지식 기반 문서를 참조하세요.link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-KBs/ONTAP_Select_node_VM_recovery_in_case_of_disaster["재해 발생 시 ONTAP Select 노드 VM 복구"^] .

.ONTAP Select 지원하는 최대 데이터 저장소 크기는 얼마입니까?
vSAN을 포함한 모든 구성은 ONTAP Select 노드당 400TB의 스토리지를 지원합니다.

지원되는 최대 크기보다 큰 데이터 저장소에 설치하는 경우 제품을 설정하는 동안 용량 제한을 사용해야 합니다.

.ONTAP Select 노드의 용량을 어떻게 늘릴 수 있나요?
ONTAP Select Deploy에는 ONTAP Select 노드에서 용량 확장 작업을 지원하는 스토리지 추가 워크플로가 포함되어 있습니다. 동일한 데이터스토어의 공간을 사용하여 관리 중인 스토리지를 확장하거나(사용 가능한 공간이 있는 경우) 별도의 데이터스토어에서 공간을 추가할 수 있습니다. 동일한 집계에서 로컬 데이터스토어와 원격 데이터스토어를 혼합하여 사용하는 것은 지원되지 않습니다.

스토리지 추가는 소프트웨어 RAID도 지원합니다. 하지만 소프트웨어 RAID의 경우 ONTAP Select VM에 물리적 드라이브를 추가해야 합니다. 이 경우 스토리지 추가는 FAS 또는 AFF 어레이를 관리하는 것과 유사합니다. 소프트웨어 RAID를 사용하여 ONTAP Select 노드에 스토리지를 추가할 때는 RAID 그룹 크기와 드라이브 크기를 고려해야 합니다.

.ONTAP Select vSAN 또는 외부 어레이 유형 데이터 저장소를 지원합니까?
ONTAP Select Deploy 및 ONTAP Select for ESX는 스토리지 풀에 vSAN 또는 외부 어레이 유형의 데이터 저장소를 사용하여 ONTAP Select 단일 노드 클러스터를 구성할 수 있도록 지원합니다.

ONTAP Select Deploy 및 ONTAP Select for KVM은 외부 어레이에서 공유 논리 스토리지 풀 유형을 사용하여 ONTAP Select 단일 노드 클러스터 구성을 지원합니다. 스토리지 풀은 iSCSI 또는 FC/FCoE를 기반으로 할 수 있습니다. 다른 유형의 스토리지 풀은 지원되지 않습니다.

공유 스토리지의 다중 노드 HA 클러스터가 지원됩니다.

.ONTAP Select 일부 HCI 스택을 포함한 vSAN이나 기타 공유 외부 스토리지에서 다중 노드 클러스터를 지원합니까?
외부 스토리지를 사용하는 다중 노드 클러스터(다중 노드 vNAS)는 ESX와 KVM 모두에서 지원됩니다. 동일 클러스터에서 하이퍼바이저를 혼합하여 사용하는 것은 지원되지 않습니다. 공유 스토리지의 HA 아키텍처는 여전히 HA 쌍의 각 노드가 파트너 데이터의 미러 복사본을 가지고 있음을 의미합니다. 그러나 다중 노드 클러스터는 VMware HA 또는 KVM Live Motion에 의존하는 단일 노드 클러스터와 달리 ONTAP 무중단 운영의 이점을 제공합니다.

ONTAP Select Deploy는 동일한 호스트에 여러 ONTAP Select VM을 지원하지만 클러스터 생성 중에는 해당 인스턴스가 동일한 ONTAP Select 클러스터에 속할 수 없습니다.ESX 환경의 경우 NetApp VMware HA가 동일한 ONTAP ONTAP Select 클러스터에서 단일 ESX 호스트로 여러 ONTAP Select VM을 마이그레이션하지 않도록 VM 반선호도 규칙을 생성할 것을 권장합니다. 또한 ONTAP Select Deploy에서 ONTAP Select VM의 관리(사용자 시작) vMotion 또는 라이브 마이그레이션으로 인해 두 개의 ONTAP Select 노드가 동일한 물리적 호스트에 위치하는 등 모범 사례를 위반한 것을 감지하면 ONTAP Select Deploy는 Deploy UI 및 로그에 알림을 게시합니다.ONTAP ONTAP Select Deploy가 ONTAP Select VM 위치를 인식하는 유일한 방법은 클러스터 새로 고침 작업을 통해서인데, 이는 ONTAP Select Deploy 관리자가 시작해야 하는 수동 작업입니다. ONTAP Select Deploy에는 사전 모니터링을 활성화하는 기능이 없으며, 알림은 Deploy UI 또는 로그를 통해서만 확인할 수 있습니다. 즉, 이 알림은 중앙 모니터링 인프라로 전달될 수 없습니다.

.ONTAP Select VMware의 NSX VXLAN을 지원합니까?
NSX-V VXLAN 포트 그룹이 지원됩니다. ONTAP MetroCluster SDS를 포함한 다중 노드 HA의 경우, VXLAN 오버헤드를 감당할 수 있도록 내부 네트워크 MTU를 7500~8900(9000 대신)으로 구성해야 합니다. 내부 네트워크 MTU는 클러스터 배포 중에 ONTAP Select Deploy를 사용하여 구성할 수 있습니다.

.ONTAP Select KVM 라이브 마이그레이션을 지원합니까?
외부 어레이 스토리지 풀에서 실행되는 ONTAP Select VM은 Virsh 라이브 마이그레이션을 지원합니다.

.vSAN AF에 ONTAP Select Premium이 필요한가요?
아니요. 외부 어레이나 vSAN 구성이 모두 플래시인지 여부에 관계없이 모든 버전이 지원됩니다.

.어떤 vSAN FTT/FTM 설정이 지원됩니까?
Select VM은 vSAN 데이터스토어 스토리지 정책을 상속하며 FTT/FTM 설정에는 제한이 없습니다. 그러나 FTT/FTM 설정에 따라 ONTAP Select VM 크기가 설정 시 구성된 용량보다 상당히 클 수 있습니다. ONTAP Select 설정 시 생성되는 Thick-eager 방식의 제로화된 VMDK를 사용합니다. 동일한 공유 데이터스토어를 사용하는 다른 VM에 영향을 주지 않으려면 Select 용량 및 FTT/FTM 설정에서 도출된 실제 Select VM 크기를 수용할 수 있도록 데이터스토어에 충분한 여유 용량을 확보하는 것이 중요합니다.

.서로 다른 Select 클러스터에 속한 여러 ONTAP Select 노드를 동일한 호스트에서 실행할 수 있습니까?
vNAS 구성의 경우에만 동일한 호스트에 여러 ONTAP Select 노드를 구성할 수 있습니다. 단, 이러한 노드가 동일한 ONTAP Select 클러스터에 속하지 않아야 합니다. DAS 구성에서는 동일한 물리적 호스트에 있는 여러 ONTAP Select 노드가 RAID 컨트롤러에 대한 액세스를 놓고 경쟁하기 때문에 이 기능이 지원되지 않습니다.

.10GE 포트 1개가 있는 호스트에서 ONTAP Select 실행할 수 있나요? ESX와 KVM 모두에서 사용할 수 있나요?
단일 10GE 포트를 사용하여 외부 네트워크에 연결할 수 있습니다. 하지만 NetApp 제한된 소형 폼 팩터 환경에서만 이 기능을 사용할 것을 권장합니다. 이 기능은 ESX와 KVM 모두에서 지원됩니다.

.KVM에서 라이브 마이그레이션을 수행하려면 어떤 추가 프로세스를 실행해야 합니까?
라이브 마이그레이션에 참여하는 각 호스트에 오픈 소스 CLVM 및 Pacemaker(PCS) 구성 요소를 설치하고 실행해야 합니다. 이는 각 호스트의 동일한 볼륨 그룹에 액세스하기 위해 필요합니다.



== vCenter

VMware vCenter와 관련된 여러 가지 질문과 답변이 있습니다.

.ONTAP Select Deploy는 vCenter와 어떻게 통신하며 어떤 방화벽 포트를 열어야 합니까?
ONTAP Select Deploy는 VMware VIX API를 사용하여 vCenter, ESX 호스트 또는 둘 다와 통신합니다. VMware 설명서에 따르면 vCenter Server 또는 ESX 호스트에 대한 초기 연결은 TCP 포트 443에서 HTTPS/SOAP를 사용하여 이루어집니다. 이 포트는 TLS/SSL을 통한 보안 HTTP를 위한 포트입니다. 두 번째로, ESX 호스트에 대한 연결은 TCP 포트 902의 소켓에서 열립니다. 이 연결을 통해 전송되는 데이터는 SSL로 암호화됩니다. 또한 ONTAP Select Deploy는 다음을 발행합니다. `PING` 지정한 IP 주소에서 응답하는 ESX 호스트가 있는지 확인하는 명령입니다.

ONTAP Select Deploy는 다음과 같이 ONTAP Select 노드 및 클러스터 관리 IP 주소와도 통신할 수 있어야 합니다.

* 핑
* SSH(포트 22)
* SSL(포트 443)


2노드 클러스터의 경우 ONTAP Select Deploy가 클러스터 사서함을 호스팅합니다. 각 ONTAP Select 노드는 iSCSI(포트 3260)를 통해 ONTAP Select Deploy에 접속할 수 있어야 합니다.

다중 노드 클러스터의 경우 내부 네트워크는 완전히 개방되어야 합니다(NAT나 방화벽 없음).

.ONTAP Select Deploy에서 ONTAP Select 클러스터를 생성하려면 어떤 vCenter 권한이 필요합니까?
필요한 vCenter 권한 목록은 여기에서 확인할 수 있습니다.link:reference_plan_ots_vcenter.html["VMware vCenter 서버"] .



== HA 및 클러스터

HA 쌍과 클러스터를 다루는 질문과 답변이 여러 개 있습니다.

.4노드, 6노드 또는 8노드 클러스터와 2노드 ONTAP Select 클러스터의 차이점은 무엇입니까?
ONTAP Select Deploy VM을 주로 사용하여 클러스터를 생성하는 4노드, 6노드, 8노드 클러스터와 달리, 2노드 클러스터는 HA 쿼럼을 위해 ONTAP Select Deploy VM을 지속적으로 사용합니다. ONTAP Select Deploy VM을 사용할 수 없는 경우 장애 조치(failover) 서비스가 비활성화됩니다.

.MetroCluster SDS란 무엇인가요?
MetroCluster SDS는 NetApp 의 MetroCluster 비즈니스 연속성 솔루션 범주에 속하는 저비용 동기식 복제 옵션입니다. FAS 하이브리드 플래시, AFF 및 NetApp 프라이빗 스토리지(클라우드용)에서 사용할 수 있는 NetApp MetroCluster 와 달리, ONTAP Select 에서만 사용할 수 있습니다.

.MetroCluster SDS는 NetApp MetroCluster 와 어떻게 다릅니까?
MetroCluster SDS는 동기식 복제 솔루션을 제공하며 NetApp MetroCluster 솔루션에 속합니다. 하지만 주요 차이점은 지원 거리(~10km 대 300km)와 연결 유형(FC 및 IP가 아닌 IP 네트워크만 지원)입니다.

.2노드 ONTAP Select 클러스터와 2노드 ONTAP MetroCluster SDS의 차이점은 무엇입니까?
2노드 클러스터는 두 노드가 서로 300m 이내의 동일한 데이터 센터에 있는 클러스터로 정의됩니다. 일반적으로 두 노드는 동일한 네트워크 스위치 또는 스위치 간 링크(Inter-Switch Link)로 연결된 네트워크 스위치 세트에 대한 업링크를 갖습니다.

2노드 MetroCluster SDS는 노드가 물리적으로 분리되어(서로 다른 방, 서로 다른 건물 또는 서로 다른 데이터 센터) 각 노드의 업링크 연결이 별도의 네트워크 스위치에 연결된 클러스터로 정의됩니다. MetroCluster SDS는 전용 하드웨어를 필요로 하지 않지만, 해당 환경은 지연 시간(5ms RTT, 5ms 지터, 최대 10ms)과 물리적 거리(10km) 측면에서 최소 요구 사항을 충족해야 합니다.

MetroCluster SDS는 프리미엄 기능이며 프리미엄 또는 프리미엄 XL 라이선스가 필요합니다. 프리미엄 라이선스는 소형 및 중형 VM과 HDD 및 SSD 미디어 생성을 지원합니다. 이러한 모든 구성이 지원됩니다.

.ONTAP MetroCluster SDS에는 로컬 스토리지(DAS)가 필요합니까?
ONTAP MetroCluster SDS는 모든 유형의 스토리지 구성(DAS 및 vNAS)을 지원합니다.

.ONTAP MetroCluster SDS는 소프트웨어 RAID를 지원합니까?
네, 소프트웨어 RAID는 KVM과 ESX 모두에서 SSD 미디어를 통해 지원됩니다.

.ONTAP MetroCluster SDS는 SSD와 회전형 미디어를 모두 지원합니까?
네, 프리미엄 라이선스가 필요하지만 이 라이선스는 소규모 및 중규모 VM과 SSD 및 회전형 미디어를 모두 지원합니다.

.ONTAP MetroCluster SDS는 4노드 이상의 클러스터 크기를 지원합니까?
아니요, Mediator가 있는 2노드 클러스터만 MetroCluster SDS로 구성할 수 있습니다.

.ONTAP MetroCluster SDS에 대한 요구 사항은 무엇입니까?
요구 사항은 다음과 같습니다.

* 3개의 데이터 센터( ONTAP Select Deploy Mediator용 1개, 각 노드용 1개)
* ONTAP Select 노드 간 최대 10ms의 총 거리와 10km의 물리적 거리를 위한 5ms RTT와 5ms 지터.
* ONTAP Select Deploy Mediator와 각 ONTAP Select 노드 사이에는 125ms RTT와 최소 5Mbps 대역폭이 필요합니다.
* 프리미엄 또는 프리미엄 XL 라이센스.


.ONTAP Select vMotion이나 VMware HA를 지원합니까?
vSAN 데이터스토어 또는 외부 어레이 데이터스토어(즉, vNAS 배포)에서 실행되는 ONTAP Select VM은 vMotion, DRS 및 VMware HA 기능을 지원합니다.

.ONTAP Select Storage vMotion을 지원합니까?
Storage vMotion은 단일 노드 및 다중 노드 ONTAP Select 클러스터와 ONTAP Select Deploy VM을 포함한 모든 구성에서 지원됩니다. Storage vMotion은 ONTAP Select 또는 ONTAP Select Deploy VM을 서로 다른 VMFS 버전(예: VMFS 5에서 VMFS 6으로) 간에 마이그레이션하는 데 사용할 수 있지만, 이 사용 사례에만 국한되지는 않습니다. Storage vMotion 작업을 시작하기 전에 VM을 종료하는 것이 가장 좋습니다. ONTAP Select Deploy는 Storage vMotion 작업이 완료된 후 다음 작업을 실행해야 합니다.

[listing]
----
cluster refresh
----
서로 다른 유형의 데이터스토어 간의 스토리지 vMotion 작업은 지원되지 않습니다. 즉, NFS 유형 데이터스토어와 VMFS 데이터스토어 간의 스토리지 vMotion 작업은 지원되지 않습니다. 일반적으로 외부 데이터스토어와 DAS 데이터스토어 간의 스토리지 vMotion 작업은 지원되지 않습니다.

.ONTAP Select 노드 간의 HA 트래픽을 다른 vSwitch 및/또는 분리된 물리적 포트를 통해 실행하거나 ESX 호스트 간에 지점 간 IP 케이블을 사용할 수 있습니까?
이러한 구성은 지원되지 않습니다. ONTAP Select 클라이언트 트래픽을 전송하는 물리적 네트워크 업링크 상태를 파악할 수 없습니다. 따라서 ONTAP Select HA 하트비트를 사용하여 클라이언트와 피어가 동시에 VM에 액세스할 수 있는지 확인합니다. 물리적 연결이 끊어지면 HA 하트비트 손실로 인해 다른 노드로 자동 장애 조치가 수행되는데, 이는 원하는 동작입니다.

HA 트래픽을 별도의 물리적 인프라에 분리하면 Select VM이 피어와는 통신할 수 있지만 클라이언트와는 통신할 수 없게 될 수 있습니다. 이로 인해 자동 HA 프로세스가 중단되고 수동 장애 조치가 실행될 때까지 데이터를 사용할 수 없게 됩니다.



== 중재 서비스

중재 서비스와 관련된 여러 가지 질문과 답변이 있습니다.

.중재자 서비스란 무엇인가요?
2노드 클러스터는 HA 쿼럼을 위해 ONTAP Select Deploy VM에 지속적으로 의존합니다. 2노드 HA 쿼럼 협상에 참여하는 ONTAP Select Deploy VM은 Mediator VM이라고 합니다.

.중재자 서비스를 원격으로 제공할 수 있나요?
네. ONTAP Select Deploy는 2노드 HA 쌍의 Mediator 역할을 하며 최대 500ms RTT의 WAN 지연 시간을 지원하고 최소 5Mbps의 대역폭이 필요합니다.

.Mediator 서비스는 어떤 프로토콜을 사용하나요?
Mediator 트래픽은 iSCSI이며, ONTAP Select 노드 관리 IP 주소에서 시작되어 ONTAP Select 배포 IP 주소에서 종료됩니다. 2노드 클러스터를 사용하는 경우 ONTAP Select 노드 관리 IP 주소에 IPv6를 사용할 수 없습니다.

.여러 개의 2노드 HA 클러스터에 하나의 Mediator 서비스를 사용할 수 있나요?
네. 각 ONTAP Select Deploy VM은 최대 100개의 2노드 ONTAP Select 클러스터에 대한 공통 Mediator 서비스 역할을 할 수 있습니다.

.배포 후에 Mediator 서비스 위치를 변경할 수 있나요?
네. 다른 ONTAP Select Deploy VM을 사용하여 Mediator 서비스를 호스팅할 수 있습니다.

.ONTAP Select Mediator가 있는(또는 없는) 확장 클러스터를 지원합니까?
확장된 HA 배포 모델에서는 Mediator가 있는 2노드 클러스터만 지원됩니다.
