---
sidebar: sidebar 
permalink: reference_plan_ots_networking.html 
keywords: plan, planning, networking, network, drivers, vmxnet3, cluster mtu, firewall 
summary: ONTAP Select 배포하기 전에 하이퍼바이저 네트워크를 올바르게 구성해야 합니다. 
---
= ONTAP Select 네트워킹 고려 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 배포하기 전에 하이퍼바이저 네트워크를 올바르게 구성해야 합니다.



== 가상 스위치 옵션

외부 네트워크와 내부 네트워크(다중 노드 클러스터만 해당)를 지원하려면 각 ONTAP Select 호스트에 가상 스위치를 구성해야 합니다. 다중 노드 클러스터를 배포하는 과정에서 내부 클러스터 네트워크의 네트워크 연결을 테스트해야 합니다.


NOTE: 하이퍼바이저 호스트에서 vSwitch를 구성하는 방법과 고속 인터페이스 기능에 대해 자세히 알아보려면 다음을 참조하세요.link:concept_nw_concepts_chars.html["심층 네트워킹"] 부분.



== VMXNET3로 업그레이드(ESXi 전용)

ONTAP Select 9.5부터 Deploy 2.10을 사용하면 VMXNET3가 VMware ESXi의 새 클러스터 배포에 포함되는 기본 네트워크 드라이버로 사용됩니다. 이전 ONTAP Select 노드를 9.5 이상 버전으로 업그레이드하면 드라이버가 자동으로 업그레이드되지 않습니다.



== 클러스터 MTU

다중 노드 클러스터에서 ONTAP Select 노드를 연결하기 위해 별도의 내부 네트워크가 사용됩니다. 일반적으로 이 네트워크의 MTU 크기는 9000입니다. 그러나 ONTAP Select 노드를 연결하는 네트워크에 비해 이 MTU 크기가 너무 큰 경우가 있습니다. 더 작은 프레임을 수용하기 위해 내부 네트워크에서 ONTAP Select 에 사용되는 MTU 크기는 7500~9000바이트 범위일 수 있습니다.

MTU 크기는 클러스터 생성 페이지의 "클러스터 세부 정보" 섹션에 표시됩니다. 이 값은 Deploy 관리 유틸리티에서 다음과 같이 결정됩니다.

. 초기 기본값은 9000입니다.
. HA 쌍에 대한 호스트와 네트워크를 추가하면 네트워크의 vSwitch 구성에 따라 MTU 값이 필요에 따라 줄어듭니다.
. 클러스터의 최종 클러스터 MTU 값은 모든 HA 쌍을 추가하고 클러스터를 생성할 준비가 된 후에 설정됩니다.



NOTE: 필요한 경우 네트워크 설계에 따라 클러스터 MTU 값을 수동으로 설정할 수 있습니다.



== 표준 vSwitch가 있는 2개의 NIC 호스트(ESXi 전용)

두 개의 NIC 구성에서 ONTAP Select 성능을 향상시키려면 두 개의 포트 그룹을 사용하여 내부 및 외부 네트워크 트래픽을 분리해야 합니다. 이 권장 사항은 다음과 같은 특정 구성에 적용됩니다.

* ONTAP Select 다중 노드 클러스터
* 두 개의 NIC(NIC1 및 NIC2)
* 표준 vSwitch


이 환경에서는 다음과 같이 두 개의 포트 그룹을 사용하여 트래픽을 구성해야 합니다.

.포트 그룹 1
* 내부 네트워크(클러스터, RSM, HA-IC 트래픽)
* NIC1가 활성화되었습니다
* 대기 상태의 NIC2


.포트 그룹 2
* 외부 네트워크(데이터 및 관리 트래픽)
* NIC1은 대기 중입니다
* NIC2가 활성화됨


를 참조하십시오link:concept_nw_concepts_chars.html["심층 네트워킹"] 2개의 NIC 배포에 대한 자세한 내용은 섹션을 참조하세요.



== 표준 vSwitch가 있는 4개 NIC 호스트(ESXi 전용)

4개의 NIC 구성에서 ONTAP Select 성능을 향상시키려면 4개의 포트 그룹을 사용하여 내부 및 외부 네트워크 트래픽을 분리해야 합니다. 이 권장 사항은 다음과 같은 특정 구성에 적용됩니다.

* ONTAP Select 다중 노드 클러스터
* 4개의 NIC(NIC1, NIC2, NIC3, NIC4)
* 표준 vSwitch


이 환경에서는 다음과 같이 4개의 포트 그룹을 사용하여 트래픽을 구성해야 합니다.

.포트 그룹 1
* 내부 네트워크(클러스터, RSM 트래픽)
* NIC1가 활성화되었습니다
* 대기 중인 NIC2, NIC3, NIC4


.포트 그룹 2
* 내부 네트워크(클러스터, HA-IC 트래픽)
* NIC3가 활성화되었습니다
* 대기 중인 NIC1, NIC2, NIC4


.포트 그룹 3
* 외부 네트워크(데이터 및 관리 트래픽)
* NIC2가 활성화되었습니다
* 대기 중인 NIC1, NIC3, NIC4


.포트 그룹 4
* 외부 네트워크(데이터 트래픽)
* NIC4가 활성화되었습니다
* 대기 중인 NIC1, NIC2, NIC3


를 참조하십시오link:concept_nw_concepts_chars.html["심층 네트워킹"] 4개의 NIC 배포에 대한 자세한 내용은 섹션을 참조하세요.



== 네트워크 트래픽 요구 사항

ONTAP Select 배포 환경에서 다양한 참여자 간에 네트워크 트래픽이 흐르도록 방화벽이 올바르게 구성되었는지 확인해야 합니다.

.참가자들
ONTAP Select 배포의 일부로 네트워크 트래픽을 교환하는 여러 참여자 또는 엔터티가 있습니다. 이러한 참여자 또는 엔터티는 소개된 후 네트워크 트래픽 요구 사항에 대한 요약 설명에 사용됩니다.

* ONTAP Select.
* vSphere(ESXi 전용) 클러스터 배포에서 호스트가 관리되는 방식에 따라 vSphere 서버 또는 ESXi 호스트입니다.
* 하이퍼바이저 서버 ESXi 하이퍼바이저 호스트 또는 Linux KVM 호스트
* OTS 노드 ONTAP Select 노드
* OTS 클러스터 ONTAP Select 클러스터
* 관리자 WS 로컬 관리 워크스테이션


.네트워크 트래픽 요구 사항 요약
다음 표에서는 ONTAP Select 배포에 필요한 네트워크 트래픽 요구 사항을 설명합니다.

[cols="20,20,35,25"]
|===
| 프로토콜/포트 | ESXi / KVM | 방향 | 설명 


| TLS(443) | ESXi | vCenter 서버(관리형) 또는 ESXi(관리형 또는 비관리형)에 배포 | VMware VIX API 


| 902 | ESXi | vCenter 서버(관리형) 또는 ESXi(관리되지 않음)에 배포 | VMware VIX API 


| ICMP | ESXi 또는 KVM | 하이퍼바이저 서버에 배포 | 핑 


| ICMP | ESXi 또는 KVM | 각 OTS 노드에 배포 | 핑 


| SSH(22) | ESXi 또는 KVM | 각 OTS 노드에 대한 관리자 WS | 관리 


| SSH(22) | 케이비엠 | 하이퍼바이저 서버 노드에 배포 | 하이퍼바이저 서버 액세스 


| TLS(443) | ESXi 또는 KVM | OTS 노드 및 클러스터에 배포 | ONTAP 에 접속하세요 


| TLS(443) | ESXi 또는 KVM | 각 OTS 노드를 배포합니다 | Access Deploy(용량 풀 라이선싱) 


| iSCSI(3260) | ESXi 또는 KVM | 각 OTS 노드를 배포합니다 | 중재자/사서함 디스크 
|===