---
sidebar: sidebar 
permalink: task_adm_connectivity.html 
keywords: administer, administering, web, connectivity, network connectivity, network checker 
summary: 내부 클러스터 네트워크에서 두 개 이상의 ONTAP Select 노드 간의 네트워크 연결을 테스트할 수 있습니다. 일반적으로 다중 노드 클러스터를 배포하기 전에 이 테스트를 실행하여 작업 실패를 유발할 수 있는 문제를 감지합니다. 
---
= ONTAP Select 노드 간 연결 확인
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
내부 클러스터 네트워크에서 두 개 이상의 ONTAP Select 노드 간의 네트워크 연결을 테스트할 수 있습니다. 일반적으로 다중 노드 클러스터를 배포하기 전에 이 테스트를 실행하여 작업 실패를 유발할 수 있는 문제를 감지합니다.

.시작하기 전에
테스트에 포함된 모든 ONTAP Select 노드는 구성되고 전원이 켜져 있어야 합니다.

.이 작업에 관하여
테스트를 시작할 때마다 백그라운드에서 새로운 프로세스 실행이 생성되고 고유한 실행 식별자가 할당됩니다. 한 번에 하나의 실행만 활성화될 수 있습니다.

테스트에는 작동을 제어하는 두 가지 모드가 있습니다.

* 빠른 이 모드는 기본적인 무중단 테스트를 수행합니다. PING 테스트와 함께 네트워크 MTU 크기 및 vSwitch 테스트가 수행됩니다.
* 확장 모드: 이 모드는 모든 중복 네트워크 경로에 대해 더욱 포괄적인 테스트를 수행합니다. 활성 ONTAP Select 클러스터에서 이 모드를 실행하면 클러스터 성능에 영향을 미칠 수 있습니다.



NOTE: 다중 노드 클러스터를 생성하기 전에 항상 빠른 테스트를 수행하는 것이 좋습니다. 빠른 테스트가 성공적으로 완료된 후, 운영 요구 사항에 따라 확장 테스트를 선택적으로 수행할 수 있습니다.

.단계
. 관리자 계정을 사용하여 Deploy 유틸리티 웹 사용자 인터페이스에 Sign in .
. 페이지 상단의 *관리* 탭을 클릭하고 *네트워크 검사기*를 클릭하세요.
. *새 실행 시작*을 클릭하고 HA 쌍에 대한 호스트와 네트워크를 선택합니다.
+
필요에 따라 추가 HA 쌍을 추가하고 구성할 수 있습니다.

. *시작*을 클릭하여 네트워크 연결 테스트를 시작하세요.

