---
sidebar: sidebar 
permalink: task_cli_connectivity.html 
keywords: administer, administering, cli, connectivity, network connectivity, network checker 
summary: 내부 클러스터 네트워크에서 두 개 이상의 ONTAP Select 노드 간의 네트워크 연결을 테스트할 수 있습니다. 일반적으로 다중 노드 클러스터를 배포하기 전에 이 테스트를 실행하여 작업 실패를 유발할 수 있는 문제를 감지합니다. 
---
= ONTAP Select 노드 간 네트워크 연결 확인
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
내부 클러스터 네트워크에서 두 개 이상의 ONTAP Select 노드 간의 네트워크 연결을 테스트할 수 있습니다. 일반적으로 다중 노드 클러스터를 배포하기 전에 이 테스트를 실행하여 작업 실패를 유발할 수 있는 문제를 감지합니다.

.시작하기 전에
테스트에 포함된 모든 ONTAP Select 노드는 구성되고 전원이 켜져 있어야 합니다.

.이 작업에 관하여
테스트를 시작할 때마다 백그라운드에서 새로운 프로세스 실행이 생성되고 고유한 실행 식별자가 할당됩니다. 한 번에 하나의 실행만 활성화될 수 있습니다.

테스트에는 작동을 제어하는 두 가지 모드가 있습니다.

* 빠른 이 모드는 기본적인 무중단 테스트를 수행합니다. PING 테스트와 함께 네트워크 MTU 크기 및 vSwitch 테스트가 수행됩니다.
* 확장 모드: 이 모드는 모든 중복 네트워크 경로에 대해 더욱 포괄적인 테스트를 수행합니다. 활성 ONTAP Select 클러스터에서 이 모드를 실행하면 클러스터 성능에 영향을 미칠 수 있습니다.



NOTE: 다중 노드 클러스터를 생성하기 전에 항상 빠른 테스트를 수행하는 것이 좋습니다. 빠른 테스트가 성공적으로 완료된 후, 운영 요구 사항에 따라 확장 테스트를 선택적으로 수행할 수 있습니다.

.단계
. 관리자 계정을 사용하여 Deploy 유틸리티 CLI에 Sign in .
. 네트워크 연결 검사기의 현재 실행을 표시하고 활성화된 실행이 없는지 확인합니다.
+
`network connectivity-check show`

. 네트워크 연결 검사기를 시작하고 명령 출력에서 실행 식별자를 기록하세요.
+
`network connectivity-check start -host-names HOSTNAMES -vswitch-type VSWITCH_TYPE-mode MODE`

+
예

+
[listing]
----
network connectivity-check start -host-names 10.234.81.14
10.234.81.15 -vswitch-type StandardVSwitch -mode quick
----
. 실행 식별자를 기반으로 네트워크 연결 검사기의 진행 상황을 모니터링합니다.
+
`network connectivity-check show -run-id RUN_ID`



.당신이 완료한 후
네트워크 연결 검사기는 일반적으로 ONTAP 내부 포트 그룹에 추가된 임시 포트와 IP 주소를 제거하여 정리합니다. 그러나 연결 검사기가 임시 포트를 제거하지 못하면 CLI 명령을 옵션과 함께 다시 실행하여 수동 정리 작업을 수행해야 합니다. `-mode cleanup` . ONTAP 내부 포트 그룹에서 임시 포트를 제거하지 않으면 ONTAP Select 가상 머신이 성공적으로 생성되지 않을 수 있습니다
