---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: Deploy 관리 유틸리티 인스턴스에 ONTAP Select 이미지를 추가할 수 있습니다. 이미지가 설치되면 ONTAP Select 클러스터를 배포할 때 사용할 수 있습니다. 
---
= 배포할 ONTAP Select 이미지 추가
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Deploy 관리 유틸리티 인스턴스에 ONTAP Select 이미지를 추가할 수 있습니다. 이미지가 설치되면 ONTAP Select 클러스터를 배포할 때 사용할 수 있습니다.

.시작하기 전에
배포에 새로운 ONTAP Select 이미지를 추가하기 전에 먼저 불필요한 이미지를 제거해야 합니다.


NOTE: Deploy 유틸리티 인스턴스에 포함된 원래 버전보다 이전 버전의 ONTAP Select 이미지만 추가해야 합니다. NetApp 에서 출시되는 ONTAP Select 의 최신 버전을 추가하는 것은 지원되지 않습니다.



== 1단계: 설치 이미지 다운로드

Deploy 유틸리티 인스턴스에 ONTAP Select 이미지를 추가하는 프로세스를 시작하려면 NetApp 지원 사이트에서 설치 이미지를 다운로드해야 합니다. ONTAP Select 설치 이미지는 단일 압축 파일로 포맷되어 있습니다.

.단계
. 웹 브라우저를 사용하여 NetApp 지원 사이트에 접속하고 *지원 빠른 링크*를 선택하세요.
. *주요 작업*에서 *소프트웨어 다운로드*를 선택하고 사이트에 로그인하세요.
. *제품 찾기*를 선택하세요.
. 아래로 스크롤하여 * ONTAP Select*를 선택하세요.
. *다른 사용 가능한 소프트웨어 선택*에서 *배포 업그레이드, 노드 업그레이드, 이미지 설치*를 선택합니다.
. 원하는 업그레이드 패키지 릴리스를 선택하세요.
. 최종 사용자 라이선스 계약(EULA)을 검토하고 *동의 및 계속*을 클릭하세요.
. 환경에 맞게 필요한 모든 프롬프트에 응답하여 적절한 패키지를 선택하고 다운로드하세요.




== 2단계: Deploy에 설치 이미지 업로드

ONTAP Select 설치 이미지를 얻은 후에는 해당 파일을 Deploy 가상 머신에 업로드해야 합니다.

.시작하기 전에
로컬 워크스테이션에 설치 이미지 파일이 있어야 합니다. 또한 Deploy 관리자 계정의 비밀번호도 필요합니다.

.이 작업에 관하여
이 작업에서는 가상 머신 배포에 파일을 업로드하는 한 가지 방법을 설명합니다. 사용자 환경에 더 적합한 다른 옵션이 있을 수 있습니다.

.단계
. 로컬 워크스테이션의 명령 셸에서 다음 예시와 같이 이미지 파일을 가상 머신 배포에 업로드합니다.
+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.결과
노드 설치 파일은 관리자의 홈 디렉토리에 저장됩니다.



== 3단계: 설치 이미지 추가

새 클러스터를 배포할 때 사용할 수 있도록 ONTAP Select 설치 이미지를 배포 이미지 디렉토리에 추가합니다.

.시작하기 전에
Deploy 유틸리티 가상 머신에서 설치 이미지 파일이 어느 디렉터리에 있는지 알아야 합니다. 해당 파일은 관리자의 홈 디렉터리에 있다고 가정합니다.

.단계
. SSH를 사용하여 관리자(admin) 계정으로 Deploy 유틸리티 CLI에 Sign in .
. Bash 셸을 시작합니다.


[listing]
----
shell bash
----
. 다음 예와 같이 설치 이미지 파일을 이미지 디렉토리에 넣습니다.
+
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== 4단계: 사용 가능한 설치 이미지 표시

새 클러스터를 배포할 때 사용할 수 있는 ONTAP Select 이미지를 표시합니다.

.단계
. Deploy 유틸리티 가상 머신에서 온라인 설명서 웹 페이지에 액세스하고 관리자(admin) 계정을 사용하여 로그인합니다.
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
배포 가상 머신의 도메인 이름이나 IP 주소를 사용하세요.

. 페이지 하단으로 이동하여 *배포*를 선택한 다음 *GET /images*를 선택합니다.
. *시도해 보세요!*를 선택하면 사용 가능한 ONTAP Select 이미지가 표시됩니다.
. 원하는 이미지가 있는지 확인하세요.

