---
sidebar: sidebar 
permalink: task_cli_migrate_deploy.html 
keywords: administer, administering, cli, deploy, deploy instance, migrate 
summary: 명령줄 인터페이스를 사용하여 Deploy 관리 유틸리티의 기존 인스턴스를 새 가상 머신으로 마이그레이션할 수 있습니다. 
---
= ONTAP Select Deploy 인스턴스를 새 가상 머신으로 마이그레이션
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
명령줄 인터페이스를 사용하여 Deploy 관리 유틸리티의 기존 인스턴스를 새 가상 머신으로 마이그레이션할 수 있습니다.

이 절차는 원래 가상 머신의 구성 데이터를 사용하는 새 가상 머신을 만드는 것을 기반으로 합니다. 새 가상 머신과 원래 가상 머신은 동일한 버전 및 릴리스의 배포 유틸리티를 실행해야 합니다. 다른 버전 및 릴리스의 배포 유틸리티로 마이그레이션할 수 없습니다.



== 1단계: 배포 구성 데이터 백업

가상 머신을 마이그레이션하는 과정에서 배포 구성 데이터의 백업을 생성해야 합니다. ONTAP Select 클러스터를 배포한 후에도 백업을 생성해야 합니다. 데이터는 암호화된 단일 파일에 저장되며, 로컬 워크스테이션에 다운로드할 수 있습니다.

.시작하기 전에
* 백업 작업 중에 Deploy가 다른 작업을 수행하지 않는지 확인하세요.
* 원본 배포 가상 머신 이미지를 저장합니다.
+

CAUTION: 이 절차의 후반부에서 원본 배포 구성 데이터를 새 가상 머신으로 복원할 때 원본 배포 가상 머신 이미지가 필요합니다.



.이 작업에 관하여
생성한 백업 파일은 가상 머신의 모든 구성 데이터를 캡처합니다. 이 데이터는 ONTAP Select 클러스터를 포함한 배포 환경의 여러 측면을 설명합니다.

.단계
. 관리자 계정으로 SSH를 사용하여 Deploy 유틸리티 CLI에 Sign in .
. Deploy 서버의 내부 디렉토리에 저장된 Deploy 구성 데이터의 백업을 만듭니다.
+
[source, cli]
----
deploy backup create
----
. 메시지가 표시되면 백업에 대한 비밀번호를 입력하세요.
+
백업 파일은 비밀번호를 기반으로 암호화됩니다.

. 시스템에서 사용 가능한 백업을 표시합니다.
+
[source, cli]
----
deploy backup show -detailed
----
. *생성* 필드의 날짜를 기준으로 백업 파일을 선택하고 *다운로드 URL* 값을 기록합니다.
+
URL을 통해 백업 파일에 접근할 수 있습니다.

. 웹 브라우저나 Curl과 같은 유틸리티를 사용하여 URL이 포함된 백업 파일을 로컬 워크스테이션에 다운로드합니다.




== 2단계: 배포 가상 머신의 새 인스턴스 설치

원래 가상 머신의 구성 데이터로 업데이트할 수 있는 배포 가상 머신의 새 인스턴스를 만들어야 합니다.

.시작하기 전에
VMware 환경에서 ONTAP Select Deploy 가상 머신을 다운로드하고 배포하는 데 사용되는 절차를 잘 알고 있어야 합니다.

.이 작업에 관하여
이 작업은 높은 수준에서 설명됩니다.

.단계
. 배포 가상 머신의 새 인스턴스를 만듭니다.
+
.. 가상 머신 이미지를 다운로드합니다.
.. 가상 머신을 배포하고 네트워크 인터페이스를 구성합니다.
.. SSH를 사용하여 Deploy 유틸리티에 액세스합니다.




.관련 정보
link:task_install_deploy.html["ONTAP Select"]



== 3단계: 배포 구성 데이터를 새 가상 머신으로 복원합니다.

원래 Deploy 유틸리티 가상 머신의 구성 데이터를 새 가상 머신으로 복원해야 합니다. 데이터는 단일 파일에 저장되어 있으며, 로컬 워크스테이션에서 업로드해야 합니다.

.시작하기 전에
이전 백업의 구성 데이터가 있어야 합니다. 해당 데이터는 단일 파일에 저장되며 로컬 워크스테이션에서 사용할 수 있어야 합니다.

.단계
. 로컬 워크스테이션의 명령 셸에서 sftp 유틸리티를 사용하여 백업 파일을 다음 예와 같이 Deploy 가상 머신에 업로드합니다.
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put deploy_backup_20190601162151.tar.gz
exit
....
. 관리자 계정으로 SSH를 사용하여 Deploy 유틸리티 CLI에 Sign in .
. 구성 데이터를 복원합니다.
+
[source, cli]
----
deploy backup restore -path <path_name> -filename <file_name>
----
+
예제 명령

+
`deploy backup restore -path /home/admin -filename deploy_backup_20180601162151.tar.gz`


